### ISSUE TITLE
[BUG] included openssl binaries report expired chain of trust for letsencrypt certificates

### ISSUE THREAD

**Issue by rasschaert** [drwetter/testssl.sh#1995] opened 2021-09-30 15:41 UTC
The root cert in the default chain (DST Root CA X3) for certificates issued by Let’s Encrypt expired today, September 30, 2021. 
Their documentation recommends upgrading to OpenSSL 1.1.0 or later: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Indeed, the older openssl binary included with testssl.sh reports expired chain of trust for all letsencrypt certificates.
```
~] ./bin/openssl.Linux.x86_64 version
OpenSSL 1.0.2-chacha (1.0.2k-dev)
```

It's perhaps best to demonstrate with https://letsencrypt.org/ itself:
```
~] ./testssl.sh https://letsencrypt.org/
...
...
 Overall Grade                T
 Grade cap reasons            Grade capped to T. Issues with the chain of trust (expired)
```

**Comment by dcooper16** [comment] 2021-09-30 17:12
Hi @rasschaert ,

Thanks for reporting. The issue seems to be:

> In OpenSSL 1.0.x, a quirk in certificate verification means that even clients that trust ISRG Root X1 will fail when presented with the Android-compatible certificate chain we are recommending by default.

As noted in https://github.com/drwetter/testssl.sh/issues/1312#issuecomment-908125442, there has been some consideration of moving testssl.sh to using a new version of OpenSSL by default. The main issue is that OpenSSL 1.0.2-chacha includes support for many old, bad cipher suites and SSL versions that were removed from newer versions of OpenSSL, so that may impact the testing of servers that still support these old cipher suites and SSL versions (and that perhaps do not support any newer, more secure options). It is definitely helpful to know about another issue related to the default use of OpenSSL 1.0.2-chacha.

**Comment by fogs** [comment] 2021-09-30 19:50
The blog post at https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/ explains the issue and gives more options to solve it besides upgrading to a newer OpenSSL version.

**Comment by mig5** [comment] 2021-10-01 05:00
Workaround that might work for people who are OK with this tool using openssl 1.1.1: add `--openssl /usr/bin/openssl` to the end of the testssl.sh command. 

This will use the system-installed openssl of the alpine distro which is 1.1.1 and passes LetsEncrypt expiry checks (as it doesn't bail on that that expired Root X3 cert, fortunately because the alternate path via the ISRG Root X1 cert is also present)

Otherwise, for the OpenSSL 1.0.2 binary: as @fogs mentioned, if you remove the DST Root CA X3 SSL cert from the trust store, and ensure the ISRG Root X1 cert is present in the trust store, everything will work. I'm about to send a PR that does just this (as well as removing the DST Root CA X3 SSL cert from the main /etc/ssl trust store, even though your custom OpenSSL 1.0.2 binary doesn't use it) - I found that I only had to update the Mozilla.pem with the latest copy of https://curl.se/ca/cacert.pem before it would work for that trust store (as well as remove the DST CA cert from the other trust stores).

**Comment by dcooper16** [comment] 2021-10-01 16:26
Thanks @fogs, @mig5,

I gave #1997 a quick try and it seems to make things better with respect to this particular expired certificate. The question is whether a more general solution is available in case a similar situation arises in the future.

Workaround 2 from https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/ might be worth considering, but it would be of limited help. It seems that adding `-trusted_first` to the `$OPENSSL verify` command line would make OpenSSL 1.0.2-chacha work more like OpenSSL 1.1.1:

>        -trusted_first
>            When constructing the certificate chain, use the trusted certificates specified via -CAfile,
>            -CApath or -trusted before any certificates specified via -untrusted.  This can be useful
>            in environments with Bridge or Cross-Certified CAs.  As of OpenSSL 1.1.0 this option is
>            on by default and cannot be disabled.

I tried using this option with OpenSSL 1.0.2-chacha, and the certificate verified correctly without needing to change the trust stores. Assuming it doesn't introduce any unexpected problems, adding this option may be beneficial as long as OpenSSL 1.0.2-chacha is the default used by testssl.sh.

The problem is that this issue is not limited to OpenSSL 1.0.2. As noted in a couple of places, this issue also affects LibreSSL, and to the degree possible we want testssl.sh to work correctly when used with LibreSSL as well. While https://community.letsencrypt.org/t/openssl-client-compatibility-changes-for-let-s-encrypt-certificates/143816 says this affects versions of LibreSSL earlier than 3.2.0 (which would include the version currently included with MacOS), verification didn't work for me even using LibreSSL 3.3.3. In addition, unlike OpenSSL 1.0.2., LibreSSL does not support the `-trusted_first` option (nor does OpenSSL 1.0.1 or earlier).

So, it may be that testssl.sh can avoid similar problems in the future when used with the default OpenSSL, either by adding the `-trusted_first` option or by making OpenSSL 1.1.1 the default, but we'll still have to deal with this on a case-by-case basis in order to make testssl.sh produce the correct results with all versions of OpenSSL and LibreSSL.

**Comment by drwetter** [comment] 2021-10-01 17:21
Thanks @dcooper16!

To be honest ``-trusted_first`` was new to me. The next to last paragraph from you sounds like it's more difficult though? At the moment it looks to me when we don't include the DST Root CA X3 root CA we should be fine for all platforms and binaries. So this sounds for now the best option.

As I read about the openssl problem my first reaction was indeed to migrate ASAP to a newer version (or a combination of both). The reason why the first hasn't been done before, I am not sure about the catches for SSLv2 and SSLv3 hosts

**Comment by dcooper16** [comment] 2021-10-01 18:10
I didn't know about `-trusted_first` either until I read the link provided by @fogs.

> As I read about the openssl problem my first reaction was indeed to migrate ASAP to a newer version (or a combination of both). The reason why the first hasn't been done before, I am not sure about the catches for SSLv2 and SSLv3 hosts

My initial reaction was also that this problem provided another reason to migrate away from OpenSSL 1.0.2-chacha. However, if simply adding the `-trusted_first` flag makes OpenSSL 1.0.2-chacha work just as well for this issue as OpenSSL 1.1.1, then its not really a reason to migrate.

It does seem that removing the DST Root CA X3 root CA is the only available option to fix the problem. I'm just not entirely happy about that since it means that the same problem could occur in the future with a different CA. We could add the `-trusted_first` flag so that the problem would only affect those using LibreSSL or a really old version of OpenSSL, but I think we want to support people using LibreSSL with testssl.sh.

**Comment by fogs** [comment] 2021-10-01 18:11
The solution with the modified trust store works well when that is under our control - like in the docker image. But it will fail (unexpectedly) if a user is running testssl.sh natively. And this will fail for all expired intermediate certificates other then the prominent DST Root CA X3. 

In my opinion, the `-trusted_first` option should be the better choice. Unless there is an impact on TLS libraries other than OpenSSL.

**Comment by smokris** [comment] 2021-10-01 20:26
> In my opinion, the -trusted_first option should be the better choice.

Thanks for the info, everyone.  I just submitted PR #1998 which adds `-trusted_first` to that test.

> Unless there is an impact on TLS libraries other than OpenSSL.

I tested it successfully with LibreSSL 2.8.3.

**Comment by drwetter** [comment] 2021-10-02 08:14
Okay, unfortunately I can't just reopen your merged and then reverted PR, @smokris .

If it still makes sense, I'd be happy to merge it, supposed @dcooper16 is happy with your PR.

**Comment by smokris** [comment] 2021-10-02 16:24
@drwetter, no problem, I just resubmitted it as #2002.

**Comment by drwetter** [comment] 2021-10-03 16:07
Closing this, your PR pending. Other one merged

**Closed as completed by drwetter** 2021-10-03 16:07 UTC
