### ISSUE TITLE
option --jsonfile-pretty produces invalid json file 

### ISSUE THREAD

**Issue by gregoryR** [drwetter/testssl.sh#1699] opened 2020-08-11 14:46 UTC
Please make sure that you provide enough information so that we understand what your issue is about.

0. Did you check the documentation in ~/doc/ or, if it is a different problem: Did you google for it?

Yes I think so

1. uname -a

```
Linux lucie 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux
```
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2

```
###########################################################
    testssl.sh       3.0 from https://testssl.sh/
```
4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'

```
/usr/bin/openssl
```

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host

Test a target that produce a scanProblem with `--json-pretty` output

```
gregr@lucie:~$ testssl.sh -S --jsonfile-pretty result.json example.com:1234
```

6. what exactly was happening, output is needed

The json output seems to be invalid and isn't parsable by `jq` or php function `json_decode`

```
gregr@lucie:~$ testssl.sh -S --jsonfile-pretty result.json example.com:1234

No engine or GOST support via engine with your /usr/bin/openssl

###########################################################
    testssl.sh       3.0 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1b  26 Feb 2019" [~79 ciphers]
 on lucie:/usr/bin/openssl
 (built: "Feb 28 09:24:20 2019", platform: "debian-amd64")


 Start 2020-08-11 16:39:27        -->> 93.184.216.34:1234 (example.com) <<--

 Further IP addresses:   2606:2800:220:1:248:1893:25c8:1946 
 rDNS (93.184.216.34):   --/usr/local/bin/testssl.sh: connect: Connexion terminée par expiration du délai d'attente
/usr/local/bin/testssl.sh: ligne 10319: /dev/tcp/93.184.216.34/1234: Connexion terminée par expiration du délai d'attente
 Oops: TCP connect problem

Unable to open a socket to 93.184.216.34:1234. 
Fatal error: Can't connect to "93.184.216.34:1234"
Make sure a firewall is not between you and your scanning target!

gregr@lucie:~$ cat result.json | jq .
parse error: Expected value before ',' at line 15, column 1
```

7. what did you expect instead?

json output to be valid.

**Note** problem doesn't occurs with the simple `--json` or `--jsonfile` options

**Comment by drwetter** [comment] 2020-08-11 20:14
Hi @gregoryR ,

you're sure you hadn't an interrupted scan before? Actually I did that by accident and it caused a similar error:

```
prompt % jsonlint result.json
result.json:15:28: Error: Unexpected text after end of JSON value
   |  At line 15, column 28, offset 778
prompt % cat result.json
{
          "Invocation"  : "testssl.sh -S --jsonfile-pretty result.json example.com:1234",
          "at"          : "XXXX:YYYY/bin/openssl.Linux.x86_64",
          "version"     : "3.0.2 d9866d8 from 2020-07-10",
          "openssl"     : "OpenSSL 1.0.2-chacha from Jan 18 17:12:17 2019",
          "startTime"   : "1597175673",
          "scanResult"  : [
                            {
                                "id"           : "scanProblem",
                                "severity"     : "FATAL",
                                "finding"      : "non-empty 'result.json' exists. Either use '--append' or (re)move it"
                           }          ],
                    "scanTime"  : "Scan interrupted"
}
                            {
                                "id"           : "scanProblem",
                                "severity"     : "FATAL",
                                "finding"      : "Can't connect to '93.184.216.34:1234'\nMake sure a firewall is not between you and your scanning target!"
                           }          ],
                    "scanTime"  : "Scan interrupted"
}
prompt % 
```

Other than that it worked for me, under 3.0.2 and 3.1dev.

**Comment by gregoryR** [comment] 2020-08-12 07:34
> you're sure you hadn't an interrupted scan before? Actually I did that by accident and it caused a similar error:

Not intentionally via `Ctrl+C` or other.

I think that the test goes to the default connection timeout.

If I force the timeout via `--connect-timeout` I get the same result. Don't really know what's happening here.

```
gregr@lucie:~$ testssl.sh -S --jsonfile-pretty result.json example.com:1234

No engine or GOST support via engine with your /usr/bin/openssl

###########################################################
    testssl.sh       3.0 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1b  26 Feb 2019" [~79 ciphers]
 on lucie:/usr/bin/openssl
 (built: "Feb 28 09:24:20 2019", platform: "debian-amd64")


 Start 2020-08-12 09:24:03        -->> 93.184.216.34:1234 (example.com) <<--

 Further IP addresses:   2606:2800:220:1:248:1893:25c8:1946 
 rDNS (93.184.216.34):   --/usr/local/bin/testssl.sh: connect: Connexion terminée par expiration du délai d'attente
/usr/local/bin/testssl.sh: ligne 10319: /dev/tcp/93.184.216.34/1234: Connexion terminée par expiration du délai d'attente
 Oops: TCP connect problem

Unable to open a socket to 93.184.216.34:1234. 
Fatal error: Can't connect to "93.184.216.34:1234"
Make sure a firewall is not between you and your scanning target!

gregr@lucie:~$ cat result.json | jq .
parse error: Expected value before ',' at line 15, column 1
gregr@lucie:~$ rm result.json 
gregr@lucie:~$ testssl.sh -S --connect-timeout 3 --jsonfile-pretty result.json example.com:1234

No engine or GOST support via engine with your /usr/bin/openssl

###########################################################
    testssl.sh       3.0 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1b  26 Feb 2019" [~79 ciphers]
 on lucie:/usr/bin/openssl
 (built: "Feb 28 09:24:20 2019", platform: "debian-amd64")


 Start 2020-08-12 09:31:04        -->> 93.184.216.34:1234 (example.com) <<--

 Further IP addresses:   2606:2800:220:1:248:1893:25c8:1946 
 rDNS (93.184.216.34):   -- Oops: TCP connect problem

Unable to open a socket to 93.184.216.34:1234. 
Fatal error: Can't connect to "93.184.216.34:1234"
Make sure a firewall is not between you and your scanning target!

gregr@lucie:~$ cat result.json | jq .
parse error: Expected value before ',' at line 15, column 1
```

**Comment by drwetter** [comment] 2020-08-12 07:47
Salut @gregoryR ,

a) you're not on the bugfixed version 3.0.2. Don't know where you got 3.0 from?

b) if an upgrade to 3.0.2 doesn't help (I think it should) please post the json file.

 Cheers, Dirk

**Comment by gregoryR** [comment] 2020-08-12 12:53
> a) you're not on the bugfixed version 3.0.2. Don't know where you got 3.0 from?

Hi @drwetter 

made some more test and there may be a nasty bug between two different debian versions.

Upgrade to testssl.sh 3.0.2 fixes the problem for debian 9 (jessie). Two different servers tested

But on debian 10 (buster) the problem is reproducible : I tested on two different servers under debian 10, the same json is produced with an extra `,` at the beginning of the `scanResult` array

You can see the json file below

```
root@vintra7:~# root@vintra7:~# testssl.sh --connect-timeout 3 --jsonfile-pretty result.json -S example.com:1234
-bash: root@vintra7:~#: command not found
root@vintra7:~# testssl.sh --connect-timeout 3 --jsonfile-pretty result.json -S example.com:1234

###########################################################
    testssl.sh       3.0.2 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~179 ciphers]
 on vintra7:/usr/local/src/testssl.sh-3.0.2/bin/openssl.Linux.x86_64
 (built: "Jan 18 17:12:17 2019", platform: "linux-x86_64")


 Start 2020-08-12 14:49:35        -->> 93.184.216.34:1234 (example.com) <<--

 Further IP addresses:   2606:2800:220:1:248:1893:25c8:1946 
 rDNS (93.184.216.34):   -- Oops: TCP connect problem

Unable to open a socket to 93.184.216.34:1234. 
Fatal error: Can't connect to "93.184.216.34:1234"
Make sure a firewall is not between you and your scanning target!

root@vintra7:~# cat result.json | jq .
parse error: Expected value before ',' at line 15, column 1
root@vintra7:~# cat result.json 
{
          "clientProblem1" : [
                            {
                                "id"           : "engine_problem",
                                "severity"     : "WARN",
                                "finding"      : "No engine or GOST support via engine with your /usr/local/src/testssl.sh-3.0.2/bin/openssl.Linux.x86_64"
                           }
          ],
          "Invocation"  : "testssl.sh --connect-timeout 3 --jsonfile-pretty result.json -S example.com:1234",
          "at"          : "vintra7:/usr/local/src/testssl.sh-3.0.2/bin/openssl.Linux.x86_64",
          "version"     : "3.0.2  from ",
          "openssl"     : "OpenSSL 1.0.2-chacha from Jan 18 17:12:17 2019",
          "startTime"   : "1597236572",
          "scanResult"  : [
,{
                                "id"           : "scanProblem",
                                "severity"     : "FATAL",
                                "finding"      : "Can't connect to '93.184.216.34:1234'\nMake sure a firewall is not between you and your scanning target!"
                           }          ],
                    "scanTime"  : "Scan interrupted"
}
```

**Comment by drwetter** [comment] 2020-08-25 07:44
Again, this unfortunately is a case of "works for me."

![Screenshot_20200825_093423](https://user-images.githubusercontent.com/8036727/91145851-60c23c80-e6b6-11ea-9dd4-0c86b3e7b792.png)

This is the recent 3.0.2, not the one released one. The git log doesn't show a difference wrt JSON fixes.

Thus I am closing this. If you have more info, pls let me know.

**Comment by gregoryR** [comment] 2020-08-27 07:15
> Again, this unfortunately is a case of "works for me."

Hi, non problem,  I perfectly understand the WFM.

As testssl.sh seems only use bash and the bash version is different on machines that produce valid / invalid json, may I ask the bash version you use

Here, Debian 9 bash 4 produces valid json

```
gregr@lucie:~$ bash -version
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>

Ceci est un logiciel libre ; vous être libre de le modifier et de le redistribuer.
AUCUNE GARANTIE n'est fournie, dans les limites permises par la loi.
```

Debian 10 bash 5 produces invalid json

```
root@vintra7:~# bash -version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by drwetter** [comment] 2020-08-27 08:03
Thanks for persistence!

**Comment by drwetter** [comment] 2020-08-27 08:07
Also it's not limited to 3.0 :-(

@dcooper16: do you understand what's going on here?

**Comment by dcooper16** [comment] 2020-08-27 13:07
Hi Dirk,

I just did some experimenting and I think I found the source of the problem, and it has nothing to do with which version of bash is being used. For me the problem occurs if `fileout_insert_warning()` is called, either because the version of OpenSSL being provided is too old or it does not have engine support.

I think the source of the problem in this part of `fileout_insert_warning()`
```
     if "$do_pretty_json"; then
          echo -e "          \"clientProblem${CLIENT_PROB_NO}\" : [" >>"$JSONFILE"
          CLIENT_PROB_NO=$((CLIENT_PROB_NO + 1))
          FIRST_FINDING=true       # make sure we don't have a comma here
     fi
     fileout "$1" "$2" "$3"
```
`FIRST_FINDING` is set to `true`, but then `fileout()` is called immediately afterwards, and it sets `FIRST_FINDING` to `false`. My guess is that the line setting `FIRST_FINDING` to `true` needs to be moved to after the call to `fileout()`, but I haven't tried testing it.

@gregoryR: If my guess is correct, when the JSON file is invalid if will include a "clientProblem1" entry, and that entry will not appear when the JSON is valid.

**Comment by dcooper16** [comment] 2020-08-27 14:49
I haven't had a chance to look at the logic behind this, but maybe rather than changing `fileout_insert_warning()` the solution would be to set `FIRST_FINDING` to `true` in `fileout_pretty_json_banner()`.

**Comment by gregoryR** [comment] 2020-08-28 03:26
> @gregoryR: If my guess is correct, when the JSON file is invalid if will include a "clientProblem1" entry, and that entry will not appear when the JSON is valid.

Hi @dcooper16 

Seems that the `clientProblem1` appears in both case on debian 10 but the json is invalid only if there is a `scanProblem`

```
⏚ [gregr:~/tmp] $ testssl.sh -S --quiet --jsonfile-pretty invalid.json example.com:1234

 Start 2020-08-28 05:11:00        -->> 93.184.216.34:1234 (example.com) <<--

 Further IP addresses:   2606:2800:220:1:248:1893:25c8:1946 
 rDNS (93.184.216.34):   --/usr/local/bin/testssl.sh: connect: Connexion terminée par expiration du délai d'attente
/usr/local/bin/testssl.sh: ligne 10319: /dev/tcp/93.184.216.34/1234: Connexion terminée par expiration du délai d'attente
 Oops: TCP connect problem

Unable to open a socket to 93.184.216.34:1234. 
Fatal error: Can't connect to "93.184.216.34:1234"
Make sure a firewall is not between you and your scanning target!

⏚ [gregr:~/tmp] 246 $ cat invalid.json 
{
          "clientProblem1" : [
                            {
                                "id"           : "engine_problem",
                                "severity"     : "WARN",
                                "finding"      : "No engine or GOST support via engine with your /usr/local/src/testssl.sh-3.0.2/bin/openssl.Linux.x86_64"
                           }
          ],
          "Invocation"  : "testssl.sh -S --quiet --jsonfile-pretty invalid.json example.com:1234",
          "at"          : "ankou:/usr/local/src/testssl.sh-3.0.2/bin/openssl.Linux.x86_64",
          "version"     : "3.0.2  from ",
          "openssl"     : "OpenSSL 1.0.2-chacha from Jan 18 17:12:17 2019",
          "startTime"   : "1598584257",
          "scanResult"  : [
,{
                                "id"           : "scanProblem",
                                "severity"     : "FATAL",
                                "finding"      : "Can't connect to '93.184.216.34:1234'\nMake sure a firewall is not between you and your scanning target!"
                           }          ],
                    "scanTime"  : "Scan interrupted"
}
⏚ [gregr:~/tmp] $ cat invalid.json | jq .
parse error: Expected value before ',' at line 15, column 1
```

On a "good" target

```
[gregr:~/tmp] $ testssl.sh -S --quiet --jsonfile-pretty valid.json gregr.fr:443

 Start 2020-08-28 05:15:28        -->> 217.70.186.106:443 (gregr.fr) <<--

[...]

 Done 2020-08-28 05:15:38 [  13s] -->> 217.70.186.106:443 (gregr.fr) <<--
⏚ [gregr:~/tmp] $ head -20 valid.json 
{
          "clientProblem1" : [
                            {
                                "id"           : "engine_problem",
                                "severity"     : "WARN",
                                "finding"      : "No engine or GOST support via engine with your /usr/local/src/testssl.sh-3.0.2/bin/openssl.Linux.x86_64"
                           }
          ],
          "Invocation"  : "testssl.sh -S --quiet --jsonfile-pretty valid.json gregr.fr:443",
          "at"          : "ankou:/usr/local/src/testssl.sh-3.0.2/bin/openssl.Linux.x86_64",
          "version"     : "3.0.2  from ",
          "openssl"     : "OpenSSL 1.0.2-chacha from Jan 18 17:12:17 2019",
          "startTime"   : "1598584525",
          "scanResult"  : [
          {
                    "targetHost"      : "gregr.fr",
                    "ip"              : "217.70.186.106",
                    "port"            : "443",
                    "rDNS"            : "gpaas6.dc2.gandi.net.",
                    "service"         : "HTTP",
```

`jq` is able to parse this file.

**Comment by drwetter** [comment] 2020-08-28 07:56
@gregoryR : yes, I saw that too. (others would have shouted out loud probably when that would not work)

@dcooper16: thanks. I tried your first advice which worked (but I saw another hopefully unrelated problem). To be honest the code also doesn't come from me and I'd feel better understanding it better before patching.

**Comment by dcooper16** [comment] 2020-08-28 14:12
> Seems that the clientProblem1 appears in both case on debian 10 but the json is invalid only if there is a scanProblem

@gregoryR : Yes, that is what I expected. I was only referring to the case in which there is a scanProblem.

The reason that is only occurs if there is a scanProblem is because of the way that `fileout_json_finding()` works.

In the normal scan, the first output in scanResult is "targetHost". Since this always comes first, a comma is never inserted before the "targetHost" entry. However, in the case of a scanProblem, "scanProblem" comes first, but it doesn't use the special code. Instead, there is code that says to insert a comma if it is the first finding. The issue is that if there is a clientPloblem, then testssl.sh thinks that the scanProblem is not the first finding and so inserts a comma.

@drwetter: Maybe I shouldn't have tried to suggest a solution. I certainly haven't looked at the code closely enough to be confident of the correct solution, which is why I didn't submit a PR. If possible, I'll try to look at this next week.

**Closed as completed** 2020-08-31 15:08 UTC
Labels: bug:minor, to be backported to 3.0
