### ISSUE TITLE
Missing comma in JSON output breaks integrity with other tools

### ISSUE THREAD

**Issue by alirezakv** [drwetter/testssl.sh#1169] opened 2018-12-03 12:50 UTC
A comma is missed in JSON output which causes other tools not be able to import the results.

testssl version: `testssl.sh       3.0rc2 from https://testssl.sh/dev/`
command used: `testssl.sh --color 0 --jsonfile=/tmp/testssl.0D0XSJ/jsonfile_child.json --openssl /opt/testssl.sh/openssl --warnings=batch 10.8.3.94:4444`
My system: `Linux kali-os 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux`
Sample JSON output:
[
         {
              "id"           : "engine_problem",
              "ip"           : "/",
              "port"         : "443",
              "severity"     : "WARN",
              "finding"      : "No engine or GOST support via engine with your testssl.sh/openssl"
          }
##a comma is missed here##
         {
              "id"           : "service",
              "ip"           : "10.8.3.94/10.8.3.94",
              "port"         : "4444",
              "severity"     : "INFO",
              "finding"      : "HTTP"
          }
,         {.....

**Comment by drwetter** [comment] 2018-12-03 13:50
the command line you posted works for me.

Did you do parallel testing or is it a problem with the kali version?

**Comment by drwetter** [comment] 2018-12-03 15:52
As said "works for me" . You gotta answer my questions if we want to move fwd

**Comment by alirezakv** [comment] 2018-12-03 16:39
You are right. It was my mistake. The command i posted works fine. The problem occurs when i pass
 "**--file**" option. I verified this with rc2 and rc3 versions.
Command: `testssl.sh --color 0 --jsonfile=jsonfile.json --openssl /opt/testssl.sh/openssl --warnings=batch --file /tmp/hosts.txt`
hosts.txt content: `10.8.3.94:4444`

**Comment by drwetter** [comment] 2018-12-04 10:18
confirmed the missing comma

**Comment by drwetter** [comment] 2018-12-04 10:45
actually the info is put in twice

```
[
         {
              "id"           : "engine_problem",
              "ip"           : "/",
              "port"         : "443",
              "severity"     : "WARN",
              "finding"      : "No engine or GOST support via engine with your [REDACTED]"
          }
         {
              "id"           : "engine_problem",
              "ip"           : "/",
              "port"         : "443",
              "severity"     : "WARN",
              "finding"      : "No engine or GOST support via engine with your [REDACTED]"
          }
,         {
              "id"           : "service",
              "ip"           : "testssl.sh/81.169.199.25",
              "port"         : "443",
              "severity"     : "INFO",
              "finding"      : "HTTP"
[..]
```

The first warning is being written into ``jsonfile.json`` without comma but also ``/tmp/testssl.XXXXXX/jsonfile_child.json`` with comma and later they are being concattenated.

**Comment by drwetter** [comment] 2018-12-11 09:11
Thx @alirezakv for reporting. Fixed now.

**Closed by drwetter** 2018-12-11 09:11 UTC
Labels: bug
