### ISSUE TITLE
Configuring the SMTP greeting String

### ISSUE THREAD

**Issue by dilyanpalauzov** [drwetter/testssl.sh#1391] opened 2019-11-23 09:02 UTC
Scanning mail servers of the concurrence has to be done from a mail server, as dynamically-looking IP addresses are locked.  The SMTP greeting must be consistent in all SMTP connections, otherwise the used iP address gets blacklisted (DNSBL) at [cbl.abuseat.org](https://www.abuseat.org/).

* Read the SMTP greeting string from a configuration file and if present, use it in line 10098: `starttls_just_send "$greet_str testssl.sh"            && debugme echo "sent $greet_str" &&`.

**Comment by drwetter** [comment] 2019-11-24 15:00
Hi Dilyan,

> Scanning mail servers of the concurrence has to be done from a mail server, as dynamically-looking IP addresses are locked

Depends on the mail server. No problems with just regular postfixes or exims out there. Organizations using appliances are more picky. A couple of Cisco ESA setups I know don't accept even the handshake when coming from dialin. Same with others I tested.

>  The SMTP greeting must be consistent in all SMTP connections

Not sure what you mean here. 

``greet_str="EHLO"``, later: ``starttls_just_send "$greet_str testssl.sh"`` . How is that not consistent?

This even is a good thing from the user perspective. A) There's a ELHO. B) It is a proper hostname C) Users use **my** hostname which has an A record (and nobody blamed me yet). And the A record also has a PTR record.

This all is not so bad, see also https://www.linuxbabe.com/mail-server/block-email-spam-postfix 

What would work better is that the IP would not be dialin -- which only the user can control.

What can be done to supply a better hostname as some servers seem to expect the EHLO hostname lookup to match somehow the IP where the client connect is coming from. But I can't tell whether this is a real life problem -- my knowledge about that is rather limited though as I dont run a large MTA.

**Comment by dilyanpalauzov** [comment] 2019-11-24 22:52
When one server is used for SMTP transactions, the MTA uses a string in the EHLO greeting, that is set for the MTA and that should be used in all SMTP transactions from that server and ideally should be the inverse PTR record of the host.

When testssl.sh starts SMTP transaction, it should use the same string, for consistency.

In practive my server has been listed at cbl.abuseat.org right after I used testssl.sh from it (I think I connected to the outlook.com mailhosts, but I am not sure) and the likely reason is that the EHLO string used by testssl.sh is no the EHLO string used by the MTA when connecting to the same hosts.

**Comment by drwetter** [comment] 2019-11-25 09:08
yeah, could do provide a configurable string via cmd line and the current setting as a efault. But it has for 99,9(% of the users no use. And for you -- if was really the case for you being blacklisted  -- you get 2-3 shots (=connects) to the other side and if you screwed it up, then you're blacklisted again. This is a "dangerous" game anyway. So you're _assuming_ you have spotted your problem.

> In practive my server has been listed at cbl.abuseat.org right after I used testssl.sh from it (I think I connected to the outlook.com mailhosts, but I am not sure) and the likely reason

"I think" and "I am not sure" is not enough for me. 

I am not an outlook.com expert but I experienced no probs at all with MX scanning. IN fact I just confirmed that I can scan two companies I know from dialin.

**Comment by dilyanpalauzov** [comment] 2019-11-25 10:01
I logged on my mail server, performed from there some ‘testssl.sh -t smtp ...:25’ calls, among others to the mailhosts of outlook.com, and later the system monitoring the appearance of the IP address in DNSBL reported, that the IP appeared at cbl.abuseat.org.

I do not remember the exact hosts to which I connected, as there is a time gap between being blacklisted and getting feedback from the monitoring (and I have not expected to be blacklisted).  So it does not really matter to which server reported to abuseat.org .

it may be that the blacklisting only happens, when fixed addresses are used, which makes sense.

The users, who use to scan 25 ports from their mail server with fixed IP address, but do not monitor that address for being on DNSBL are the ones with problem.

**Comment by drwetter** [comment] 2019-11-26 08:39
I used a fix IP to scan ``--mx outlook.com``, I wasn't blocked. From dialin this one (other then the hosted office365 from companies) I wasn't even able to scan:

```
rDNS (104.47.56.161):   --
 STARTTLS handshake failed
 STARTTLS handshake failed
 STARTTLS handshake failed
 STARTTLS handshake failed
 STARTTLS handshake failed
 STARTTLS handshake failed
```

I am closing this because it seems to me consulting a crystal ball when something will be blocked. If something makes sense and there's _evidence_ I am happy to reopen.

**Closed by drwetter** 2019-11-26 08:39 UTC
