### ISSUE TITLE
../testssl.sh: line 4343: [[: 2F99: value too great for base (error token is "2F99")

### ISSUE THREAD

**Issue by matteocorti** [drwetter/testssl.sh#348] opened 2016-05-11 13:54 UTC
When testing uc13.ethz.ch I get

`../testssl.sh: line 4343: [[: 2F99: value too great for base (error token is "2F99")
`
Debugging output:

```
  SSLv3      sending client hello...
"\x16\x03\x00\x00\xcb\x01\x00\x00\xc7\x03\x00\x54\x51\x1e\x7a\xde\xad\xbe\xef\x31\x33\x07\x00\x00\x00\x00\x00\xcf\xbd\x39\x04\xcc\x16\x0a\x85\x03\x90\x9f\x77\x04\x33\xd4\xde\x00\x00\xa0\xc0\x14\xc0\x0a\xc0\x22\xc0\x21\xc0\x20\x00\x39\x00\x38\x00\x37\x00\x36\x00\x88\x00\x87\x00\x86\x00\x85\xc0\x0f\xc0\x05\x00\x35\x00\x84\xc0\x13\xc0\x09\xc0\x1f\xc0\x1e\xc0\x1d\x00\x33\x00\x32\x00\x80\x00\x81\x00\x82\x00\x83\x00\x31\x00\x30\x00\x9a\x00\x99\x00\x98\x00\x97\x00\x45\x00\x44\x00\x43\x00\x42\xc0\x0e\xc0\x04\x00\x2f\x00\x96\x00\x41\x00\x07\xc0\x11\xc0\x07\x00\x66\xc0\x0c\xc0\x02\x00\x05\x00\x04\xc0\x12\xc0\x08\xc0\x1c\xc0\x1b\xc0\x1a\x00\x16\x00\x13\x00\x10\x00\x0d\xc0\x0d\xc0\x03\x00\x0a\x00\x63\x00\x15\x00\x12\x00\x0f\x00\x0c\x00\x62\x00\x09\x00\x65\x00\x64\x00\x14\x00\x11\x00\x0e\x00\x0b\x00\x08\x00\x06\x00\x03\x00\xff\x01\x00"
reading server hello...
00000000  30 2f 99 16 00 00 00 00  50 a0 42 0b 00 00 00 00  |0/......P.B.....|
00000010  21 16 a0 d4 d9 b9 b1 8b  e2 d3 ee 4f 0d c3 d8 0d  |!..........O....|
00000020  b8 9c 55 91 65 e7 1b 90  d1 8a 25 03 d4 a8 cd 1f  |..U.e.....%.....|
00000030  2f 08 45 23 c9 16 df ae  64 1d 0f f3 4c b8 18 1e  |/.E#....d...L...|
00000040  8f 9a ff e6 06 5b 97 05  d9 42 99 c6 41 7a b4 d3  |.....[...B..Az..|
00000050  6e fe 54 85 4f b5 0f 4d  31 64 3d ef 04 78 5b 90  |n.T.O..M1d=..x[.|

tls_protocol (reclyr):  0x2F99
tls_hello:              0x00
tls_protocol:           0xA042
tls_sid_len:            0x3 / = 3
tls_hello_time:         0x0B000000 1975-11-07 12:42:56 AM
tls_cipher_suite:       0x1F2F
tls_compression_method: 0x08

./testssl.sh: line 4343: [[: 2F99: value too great for base (error token is "2F99")
  (returned 184 lines)  protocol send: 0x0300, returned: 0x2F99
#FIXME: downgraded. still missing a test case here
 TLS 1      sending client hello...
```

Similarly when testing  129.132.101.40

```
 SSLv3      ./testssl.sh: line 4343: [[: 41AB: value too great for base (error token is "41AB")
```

```
 SSLv3      sending client hello...
"\x16\x03\x00\x00\xcb\x01\x00\x00\xc7\x03\x00\x54\x51\x1e\x7a\xde\xad\xbe\xef\x31\x33\x07\x00\x00\x00\x00\x00\xcf\xbd\x39\x04\xcc\x16\x0a\x85\x03\x90\x9f\x77\x04\x33\xd4\xde\x00\x00\xa0\xc0\x14\xc0\x0a\xc0\x22\xc0\x21\xc0\x20\x00\x39\x00\x38\x00\x37\x00\x36\x00\x88\x00\x87\x00\x86\x00\x85\xc0\x0f\xc0\x05\x00\x35\x00\x84\xc0\x13\xc0\x09\xc0\x1f\xc0\x1e\xc0\x1d\x00\x33\x00\x32\x00\x80\x00\x81\x00\x82\x00\x83\x00\x31\x00\x30\x00\x9a\x00\x99\x00\x98\x00\x97\x00\x45\x00\x44\x00\x43\x00\x42\xc0\x0e\xc0\x04\x00\x2f\x00\x96\x00\x41\x00\x07\xc0\x11\xc0\x07\x00\x66\xc0\x0c\xc0\x02\x00\x05\x00\x04\xc0\x12\xc0\x08\xc0\x1c\xc0\x1b\xc0\x1a\x00\x16\x00\x13\x00\x10\x00\x0d\xc0\x0d\xc0\x03\x00\x0a\x00\x63\x00\x15\x00\x12\x00\x0f\x00\x0c\x00\x62\x00\x09\x00\x65\x00\x64\x00\x14\x00\x11\x00\x0e\x00\x0b\x00\x08\x00\x06\x00\x03\x00\xff\x01\x00"
reading server hello...
00000000  30 41 ab 06 00 00 00 00  40 af 2c 0a 00 00 00 00  |0A......@.,.....|
00000010  8d 6a 4b f0 31 84 72 2b  01 ca 30 93 16 7b e0 ad  |.jK.1.r+..0..{..|
00000020  ec a8 ea 11 6b b1 32 23  99 08 be 89 8a 22 a0 eb  |....k.2#....."..|
00000030  2b de 06 1d 9f 16 88 9f  e7 1e cf 21 41 8c ca 2d  |+..........!A..-|
00000040  d4 b6 b1 ba 74 fd 80 73  d4 c8 c6 98 8f 54 af 77  |....t..s.....T.w|
00000050  bc e6 0f e4 d3 8a 56 38  8e db a2 60 e5 d3 3f 76  |......V8...`..?v|

tls_protocol (reclyr):  0x41AB
tls_hello:              0x00
tls_protocol:           0xAF2C
tls_sid_len:            0x311 / = 137
tls_hello_time:         0x0A000000 1975-04-26 08:22:40 PM
tls_cipher_suite:       0x4C69
tls_compression_method: 0x6D

  (returned 184 lines)  ./testssl.sh: line 4343: [[: 41AB: value too great for base (error token is "41AB")
protocol send: 0x0300, returned: 0x41AB
#FIXME: downgraded. still missing a test case here
```

**Comment by drwetter** [comment] 2016-05-12 05:17
Hi @matteocorti,

can't reproduce that with  ``4eefe0d 2016-05-11 00:14:24 -- 1.481``. Which version did you use?

Cheers, Dirk

**Comment by matteocorti** [comment] 2016-05-12 07:16
Hi Dirk

I am using 4eefe0df8b1de03446126d4a6831b18172bc5d3c on OS X (10.11) or Linux (Fedora 23 and CentOS 7.2).

**Comment by dcooper16** [comment] 2016-05-12 15:13
I'm getting a response similar to @matteocorti (see below). I also tried using OpenSSL, and it gets a similar response. The biggest problem is that this isn't an SSL/TLS message. It should begin with something of the form:
```
      struct {
          ContentType type;
          ProtocolVersion version;
          uint16 length;
          opaque fragment[TLSPlaintext.length];
      } TLSPlaintext;
```
but it doesn't. So, testssl.sh is trying to parse an SSL/TLS response, but is getting confused since that is not what the server provides. The response is very odd. It contains most of the server's certificate and most of the CA certificate that would precede this certificate in a path, but neither certificate appears in its entirely. For the server's certificate, the first 11 bytes are missing. The contents of the certificate begin at around byte 108 in the response. It have no idea how the first 107 bytes of the response were created or why the first 11 bytes of the certificate are missing.

In any case, it seems testssl.sh could be changed to present a different error response, but it can't accept this as a valid SSL/TLS message.

```
bash myforks/testssl_all.sh --openssl=mygitfork/testssl.sh/bin/openssl.Linux.x86_64-krb5 --debug 5 --ip 129.132.101.40 --debug 5 --devel 00 "00,35" uc13.ethz.ch

sending client hello...
"\x16\x03\x00\x00\x2d\x01\x00\x00\x29\x03\x00\x54\x51\x1e\x7a\xde\xad\xbe\xef\x31\x33\x07\x00\x00\x00\x00\x00\xcf\xbd\x39\x04\xcc\x16\x0a\x85\x03\x90\x9f\x77\x04\x33\xd4\xde\x00\x00\x02\x00\x35\x01\x00"
reading server hello...
00000000  10 80 00 0b 00 00 00 00  70 f0 6c 06 00 00 00 00  |........p.l.....|
00000010  27 6d d0 3d 23 0d 5a c7  22 67 77 81 07 d4 6e ff  |'m.=#.Z."gw...n.|
00000020  71 3d 81 f6 8c 68 14 98  13 f7 7d 99 10 c3 01 13  |q=...h....}.....|
00000030  b7 1b 23 a7 01 4e 18 34  cc 83 f3 53 7c 73 d1 70  |..#..N.4...S|s.p|
00000040  1d 20 ef 94 a4 5f 14 2b  1e ad 85 9f 15 75 48 d3  |. ..._.+.....uH.|
00000050  c6 b6 9b cf a8 6b 67 f6  ac e4 11 a1 50 ac 58 8c  |.....kg.....P.X.|

1080000B0000000070F06C0600000000276DD03D230D5AC72267778107D46EFF713D81F68C68149813F77D9910C30113B71B23A7014E1834CC83F3537C73D1701D20EF94A45F142B1EAD859F157548D3C6B69BCFA86B67F6ACE411A150AC588C93D55ED1285A8CE9C37DFF010202142C380B67C479AECF1B009E7F6C98A9F08F89E2EB300D06092A864886F70D01010B0500304D310B300906035504061302424D31193017060355040A131051756F5661646973204C696D69746564312330210603550403131A51756F566164697320476C6F62616C2053534C20494341204732301E170D3134313131323135303532365A170D3136313131323135303531385A305C310B30090603550406130243483110300E060355040813075A7565726963683110300E060355040713075A75657269636831143012060355040A130B455448205A756572696368311330110603550403130A75632E6574687A2E636830820122300D06092A864886F70D01010105000382010F003082010A0282010100C40EA26B00B6FEEFDB19BD07A6C75CA687EC889FE56759F7D9D88E8E01DA018CF86F1CDBC7DC905C95617DFDCE19DDD7889AF4FC421D3891C6597445FD9E832E75D64DD19F932B282063451DF0F26484355814F1251A1DFCEE5A36E2CA276E1947BAD1004D62ACAB82FC78A0E9BF8040CE2A4BD5E00858DF1648C756AAE8BEBB1F819090D4B163189935F8B0EEC7A9C638937B6B2D1F0ED70EEBE5F148F694755B2FDBBCC206626C202BF9E16B6AD59D14C6DE9E3FB134595D3D378C4B6313ABFC14910F7442BEACC411D771A0D95A9C396406900B8F2A86FE7B32FB4BB8643F9D5FF89B4C5AF76FE3AA7D9FDDAC0D1AB38F4E05134FFCAE931AEFF13A32686D0203010001A382020F3082020B307306082B0601050507010104673065302A06082B06010505073001861E687474703A2F2F6F6373702E71756F7661646973676C6F62616C2E636F6D303706082B06010505073002862B687474703A2F2F74727573742E71756F7661646973676C6F62616C2E636F6D2F717673736C67322E6372743081950603551D1104818D30818A820A75632E6574687A2E6368820D75632E69642E6574687A2E6368820A61762E6574687A2E6368820C636F6E662E6574687A2E6368820C756331332E6574687A2E6368820F756331332E69642E6574687A2E6368820C617631332E6574687A2E6368820E636F6E6631332E6574687A2E636881167469626F722E6D61676F634069642E6574687A2E636830510603551D20044A30483046060C2B06010401BE5800026401013036303406082B060105050702011628687474703A2F2F7777772E71756F7661646973676C6F62616C2E636F6D2F7265706F7369746F7279300E0603551D0F0101FF0404030205A0301D0603551D250416301406082B0601050507030106082B06010505070302301F0603551D23041830168014911962AD5B17A730FBF0DE3925B1BD8CB9B85127303A0603551D1F04333031302FA02DA02B8629687474703A2F2F63726C2E71756F7661646973676C6F62616C2E636F6D2F717673736C67322E63726C301D0603551D0E04160414F087DF5656CC3F4A552C360206E7C3EEA85E87C2300D06092A864886F70D01010B05000382010100A49B5F81A56A33A1477EACF39A7130AC3576F4D3998965B3DB7B3F26642DE3C169719DB9E0BAD734A490CC582FFEC5A5E30C9AA17E066FAD607648769D9A34D565F06B39A053F597A5CB2F5D1592CA18DE8ED76BBF20E5C3044463200A5187C5E26535B5B0B4DDF204F8A0E17706D1341C3BF7FFD555318F3C62FA15020C815FDDFEF5373B56DAC24D38FBB35BDCBB0A954C2E2DC0370DCD3F1E9855AB3298AE1449D8BD07D694E3BEEC335AAE785B582FA26B0FB716DE6FA3FA4E60FF438C5BECEA60A6951DE040D466678E57AFA2852306DB720A21D4EF873ACCB67807139EAAFFBF669571656896E1C461525376634E5332DB3BF7951E2EC902729C76F05B0005503082054C30820334A003020102021448982DE2A92CB339E1C8F933358275D3E4F88255300D06092A864886F70D01010B05003045310B300906035504061302424D31193017060355040A131051756F5661646973204C696D69746564311B30190603550403131251756F566164697320526F6F742043412032301E170D3133303630313133333530355A170D3233303630313133333530355A304D310B300906035504061302424D31193017060355040A131051756F5661646973204C696D69746564312330210603550403131A51756F566164697320476C6F62616C2053534C2049434120473230820122300D06092A864886F70D01010105000382010F003082010A0282010100E1E1856994C08F57FA34FEC1B868E49990A9887ACE57B7D0E4B554C2187DD0C319E8A96380F7B7DCD219A35AB060D976B41D325635F16CA39C42A18B8A233597417B056984288ECE1E4D8B6024F1B488FEC050F6C28FAE9774F940AA6EF686B3A4E9C75F746514F43DDCBE4EA398645FE3066CC18FB61F5C9996C657C2CBAD94890EADBEFFB80BA5B638FBB54781D40FCA09F10A3B120D1C0FE185B01336C3CB287DFCA5F8373AA4AB404663829540BB12AC963F457DF79DE5037E24B89665631C5D8208414E7F6B5A8690C3F2EBE459F45E077B7D84B7FF31A199762F56CB80C489FC1A4F9869EA0B67C1FDB54BE70C3DE5107CEF22C30FC6AB5DEC881C55A30203010001A382012A3082012630120603551D130101FF040830060101FF02010030110603551D20040A300830060604551D2000307206082B0601050507010104663064302A06082B06010505073001861E687474703A2F2F6F6373702E71756F7661646973676C6F62616C2E636F6D303606082B06010505073002862A687474703A2F2F74727573742E71756F7661646973676C6F62616C2E636F6D2F7176726361322E637274300E0603551D0F0101FF040403020106301F0603551D230418301680141A8462BC484C332504D4EED0F603C41946D1946B30390603551D1F04323030302EA02CA02A8628687474703A2F2F63726C2E71756F7661646973676C6F62616C2E636F6D2F7176726361322E63726C301D0603551D0E04160414911962AD5B17A730FBF0DE3925B1BD8CB9B85127300D06092A864886F70D01010B050003820201007C0A60820041B52DCC39E5F4DB6BCE008A9C0C89E6727453B96DC221E54C975A0599E8E3F88DBFFA2DA89F10C2E34420B4994D781BA3EB3D4FA265088869EED7E446AF866113100F096CB2028E20F873D63AF9B80CB78B3310F899D9200B3908F5D01AF81CA41FCBF3AF6DE7516CB6B1A7DAA50C6E2A2604ADDEE8A40C82526ABC7A9A9804417BB4D1464D92211851F78EF215C65EB65BB439E4B9A8950ED33AB3DC98A5CA3217114EACE46B120562688ECFDC425A0D8988E880D420F69204CE86AD532268835810C04BD6FDA3662F2B5C3634C95B19FF40C021088204D36F4F53634394A7D44F8EF99062A830FEAC1BC1A0FB08EB275F74AB49BABE582FE3A89092B678BADC7BCDBCEDAC0871DF053110DC670FCD5F56DCF2E2B27B9382B70A50D1DE232F87A6B97C05BFC4EA51B661DB1252872CB9EDCAB0DEA5A804EB3F596CDADBDFC7BA7F0F5E442865EA7063FC5CFBD9C8D4D68A33C36A852A89353265BD78FBCDBDE67696DEDD847D0644973EBA2537B97928EC79E2027B909EEBEAA25826EC74DC7C8F335D4AA78C1F767D51B02D944396B00BA7E0FF75C4D87655932A898CAC2A8789C56A22B910C57B0C7438A09C7D724983C3AA
tls_protocol (reclyr):  0x8000
tls_hello:              0x00
tls_protocol:           0xF06C
tls_sid_len:            0x339 / = 153
tls_hello_time:         0x06000000 1973-03-10 09:01:36 PM
tls_cipher_suite:       0x131A
tls_compression_method: 0x51

  (returned 173 lines)  protocol send: 0x0300, returned: 0x8000
```

**Comment by drwetter** [comment] 2016-05-13 05:40
sorry, can reproduce it too now.

Yes, it should not accept this. Validation (sigh) is not good enough here. It should be caught way earlier in the code like "if server hello first byte is not "x16|x15|.." return an error.

**Comment by dcooper16** [comment] 2016-05-13 17:47
@drwetter,

In the code that I've been working on at https://github.com/dcooper16/testssl.sh/blob/extended_tls_sockets/testssl.sh, parse_tls_serverhello() does a lot of error checking on the response (I just added many additional checks today). The main reason that I've been working on rewriting parse_tls_serverhello() is so that tls_sockets() can be used in a lot of the places where $OPENSSL s_client is currently used. Since it's such a major rewrite and since it's primarily intended to support future enhancements, my plan has to to wait until after the 2.8 release to submit a PR.

Should I stick with that plan, or would you like me to submit a PR now with some of the code from parse_tls_serverhello() (and any necessary related code changed) in https://github.com/dcooper16/testssl.sh/blob/extended_tls_sockets/testssl.sh in order to address the need to catch errors such as this? Note that this would address the issue that I raised in #340.

**Comment by drwetter** [comment] 2016-05-14 09:43
Hi David,


Am 13. Mai 2016 19:47:30 MESZ, schrieb David Cooper <notifications@github.com>:
>@drwetter,
>
>In the code that I've been working on at
>https://github.com/dcooper16/testssl.sh/blob/extended_tls_sockets/testssl.sh,
>parse_tls_serverhello() does a lot of error checking on the response (I
>just added many additional checks today). The main reason that I've
>been working on rewriting parse_tls_serverhello() is so that
>tls_sockets() can be used in a lot of the places where $OPENSSL
>s_client is currently used. Since it's such a major rewrite and since
>it's primarily intended to support future enhancements, my plan has to
>to wait until after the 2.8 release to submit a PR.
>
>Should I stick with that plan, or would you like me to submit a PR now
>with some of the code from parse_tls_serverhello() (and any necessary
>related code changed) in
>https://github.com/dcooper16/testssl.sh/blob/extended_tls_sockets/testssl.sh
>in order to address the need to catch errors such as this? Note that
>this would address the issue that I raised in #340.


Please go ahead with the PR. This (#348) is a bug and needs to be addressed anyway. I would have done otherwise a quick validation, less solid than your approach.

Could you do a solid round of testing for a number of hosts and diff the output too?

Cheers, Dirk 



-- 
Set from my mobile. Excuse my brevity&typos

**Comment by drwetter** [comment] 2016-05-18 16:45
closing, see #353.

Thx for reporting, @matteocorti

**Closed** 2016-05-18 17:07 UTC
Labels: bug
