### ISSUE TITLE
"No engine or GOST support via engine with your (...)/testssl.sh/bin/openssl.Linux.x86_64"

### ISSUE THREAD

**Issue by jandr** [drwetter/testssl.sh#1119] opened 2018-09-10 11:57 UTC
I am using  testssl.sh 3.0rc1

###########################################################
    testssl.sh       3.0rc1 from https://testssl.sh/dev/
    (4457054 2018-09-10 09:52:59 -- )

When starting new scans, I am getting a purple error message stating that: 

"No engine or GOST support via engine with your /path/to/testssl.sh/bin/openssl.Linux.x86_64"

This had never happened before, and to the openssl binary was not updated in the last git pull I did, which can be seen below: 

```From https://github.com/drwetter/testssl.sh
   d83aed8..4457054  2.9dev     -> origin/2.9dev
   452f433..1b06d6e  2.9.5      -> origin/2.9.5
 * [new tag]         v2.9.5-7   -> v2.9.5-7
 * [new tag]         3.0rc1     -> 3.0rc1
 * [new tag]         v2.9.5-6   -> v2.9.5-6
Updating d83aed8..4457054
Fast-forward
 Dockerfile            |   1 +
 doc/testssl.1         |  10 ++++----
 doc/testssl.1.html    |  10 ++++----
 doc/testssl.1.md      |   8 +++----
 etc/common-primes.txt | 226 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------------------------------------------------------
 testssl.sh            | 304 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------------
 6 files changed, 306 insertions(+), 253 deletions(-)
```

I am using the openssl version shipped with testssl.sh: 

```
 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~179 ciphers]
 on <hostname>:/path/to/testssl.sh/bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")
```

I am using Debian, `4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux`

**Comment by drwetter** [comment] 2018-09-10 15:45
understand it's confusing and it may also confuse others. Found a way to kind of detect a 1.1.1 config file.

**Comment by drwetter** [comment] 2018-09-10 15:57
Fixed now

**Closed by drwetter** 2018-09-10 15:57 UTC

**Comment by shaaati** [comment] 2020-04-21 18:27
I just stumbled upon this today. Recently, I started generating reports with the `-oA` command line option. While the warning is not present in either .html or .log output, it is shown in the .csv and .json output files.
I use a recent Kali Linux and so I guess the "Debian Testing" aspects apply.
I had a look at #1117 and #1098 and understand that GOST is "not that" important in real world scenarios.
What I don't yet fully understand is whether or not this issue actually exists for Debian Testing users.
There seems to be a reason that you decided to remove the warning from the output in case that OpenSSL 1.1.1 is detected.
Is the warning a false-positive on Debian testing systems? Or did you decide to suppress it because it will always be shown in Debian Testing while not having a high practical relevance? In the latter case, it might be better to explain the warning to the user instead of suppressing it.

As your intention for the commit 1bfc9ca is to not confuse users I think it might be reasonable to also suppress the warning in the output file formats if it has no practical effect.

**Comment by drwetter** [comment] 2020-04-21 18:50
> Is the warning a false-positive on Debian testing systems

A warning in terms of testssl.sh is not a finding thus it cannot be a false positive. It's just a hint that the openssl used cannot load a shared external encryption library which was the case on older systems.

I have no Debian testing handy thus I cannot tell whether there's a problem. But I assume it is not different as on Debian Buster. Which is it has little effect on the result., outside Russia at least. IIRC It has only an effect when you're testing a server which **only** has 2(?) GOST ciphers. And there only in the section headers, maybe renegotiation and little more.

**Comment by shaaati** [comment] 2020-04-22 12:58
Maybe the term "false positive" was misleading. What I meant is:
Does the warning in all cases mean that the library really could not be loaded?
Or can there be cases in which the library is loaded correctly, but the warning is shown anyway? From the discussions around Debian testing I didn't understand if there actually is an issue or if openssl only *thinks* that something is wrong.

Anyway, I think it would make sense to either suppress the warning everywhere, that is, also in the `.csv` and `.json` output, or show it everywhere and clearly explain to the user that it will likely have no practical effect.

For me, finding the warning in the output files originally lead to confusion and raised multiple questions. Why was it shown there but not in the stdout output? Would it impact the quality of my test results? How many of my tests in the past would have been impacted?
Maybe the warning could be reworded like you mentioned in your last comment: "This has little effect on the result, outside Russia at least."

**Comment by bl4ck5un** [comment] 2020-07-09 18:04
stumbled upon this using the brew package with openssl 1.1.1g and 

```
testssl.sh       3.0.2 from https://testssl.sh

 Using "OpenSSL 1.1.1g  21 Apr 2020" [~80 ciphers]
 on YYY:/usr/local/opt/openssl@1.1/bin/openssl
 (built: "Apr 21 13:30:00 2020", platform: "darwin64-x86_64-cc")
```

**Comment by bl4ck5un** [comment] 2020-07-09 18:07
For me, even though I don't care about GOST, the warning reads as if the issue is not specific to GOST.

**Comment by dcooper16** [comment] 2020-07-16 15:54
> Which is it has little effect on the result., outside Russia at least. IIRC It has only an effect when you're testing a server which only has 2(?) GOST ciphers. And there only in the section headers, maybe renegotiation and little more.

If the lack of engine or GOST support in $OPENSSL only affects GOST-only servers, could we perhaps avoid some of the confusion by only displaying the warning if dealing with a potentially GOST-only server. The idea would be:

- `initialize_engine()` would just set a variable rather than issuing a warning.
- if `determine_optimal_sockets_params()` connects to the server with a GOST cipher, then set a variable indicating that the server supports GOST.
- if `determine_optimal_proto()` gets to the point where it determines that `$all_failed` with `$OPENSSL` but not `$ALL_FAILED_SOCKETS`, then issue the warning if the server supports GOST.

**Comment by drwetter** [comment] 2020-07-16 17:43
We should remove the warning upfront completely. For other servers where openssl has not the ciphers builtin we don't do that either, maybe later.

For the later: yes, we could do that. Wondering though whether we should

**Comment by moralrebuild** [comment] 2020-08-11 08:13
any quick solution?

**Comment by drwetter** [comment] 2020-08-11 10:25
see PR #1688

**Comment by Verequies** [comment] 2021-03-08 02:44
Just looking into this warning on my system. Am a bit confused what is going on with the checks here. I noticed that if I don't have GOST compiled in, and I run 'openssl engine gost -vvvv -t' I get an error, however if I run 'openssl engine -vvvv -t' I don't. 

Should we be checking if GOST is supported separately rather than at the same time? This could potentially fix the warning. Or as already done hide it. Could possibly list it under supported features somewhere whether you have GOST enabled or not.

**Comment by drwetter** [comment] 2021-03-08 13:21
Could you state please where this warning still happens?

As said elsewhere, this warning was only there because if a server supports only the ~two ciphers which the engine plugin delivered we are not able to do checks beyond TLS/SSL like HTTP headers.

**Comment by Verequies** [comment] 2021-03-09 00:54
Sorry I didn't explain myself very well in the previous message. I'm still using understand the recent commit where you have hidden the warning behind a debug flag. Which is confirmed when I compile 3.1dev. I was just looking into trying to configure my system in order to hide the warning but couldn't figure it out.

'openssl engine -vvvv -t' clearly shows there is an engine available:
```
(rdrand) Intel RDRAND engine
     [ available ]
(dynamic) Dynamic engine loading support
     [ unavailable ]
     SO_PATH: Specifies the path to the new ENGINE shared library
          (input flags): STRING
     NO_VCHECK: Specifies to continue even if version checking fails (boolean)
          (input flags): NUMERIC
     ID: Specifies an ENGINE id name for loading
          (input flags): STRING
     LIST_ADD: Whether to add a loaded ENGINE to the internal list (0=no,1=yes,2=mandatory)
          (input flags): NUMERIC
     DIR_LOAD: Specifies whether to load from 'DIR_ADD' directories (0=no,1=yes,2=mandatory)
          (input flags): NUMERIC
     DIR_ADD: Adds a directory from which ENGINEs can be loaded
          (input flags): STRING
     LOAD: Load up the ENGINE specified by other settings
          (input flags): NO_INPUT
```

However errors when specifying 'openssl engine gost -vvvv -t' when not compiled in:
```
119090621363584:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/engines-1.1/gost.so): /usr/lib/engines-1.1/gost.so: cannot open shared object file: No such file or directory
119090621363584:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
119090621363584:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
119090621363584:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:334:id=gost
```
It appears in the following code we're only checking for GOST and not other engines, perhaps they should be checked separately?

Unless this entire bit of code is just checking for GOST support, and in that case the warning should be changed to something such as "No GOST engine support with your $OPENSSL". This would at least clear the confusion up for me. And in fact you might not even have the warning and just list it somewhere in the output "GOST Engine: Not supported".

Not sure how to reference lines in the source code as it is quite big so just copied and pasted the second I'm referring to here:
```
initialize_engine(){
     # for now only GOST engine
     grep -q '^# testssl config file' "$OPENSSL_CONF" 2>/dev/null && \
          return 0        # We have been here already
     if "$NO_ENGINE"; then
          # Avoid potential conflicts also -- manual hook, see #1117
          export OPENSSL_CONF=''
          return 1
     elif $OPENSSL engine gost -v 2>&1 | grep -Eq 'invalid command|no such engine'; then
          [[ "$DEBUG" -ge 1 ]] && outln && pr_warning "No engine or GOST support via engine with your $OPENSSL"; outln
          fileout_insert_warning "engine_problem" "WARN" "No engine or GOST support via engine with your $OPENSSL"
          export OPENSSL_CONF=''
          return 1
     elif ! $OPENSSL engine gost -vvvv -t -c 2>/dev/null >/dev/null; then
          # check for openssl 1.1.1 config -- not this may not be reliable. We only use this
          # to suppress the warning (confuses users), see #1119
          # https://github.com/openssl/openssl/commit/b524b808a1d1ba204dbdcbb42de4e3bddb3472ac
          if ! grep -q 'using the .include directive' /etc/ssl/openssl.cnf; then
               [[ "$DEBUG" -ge 1 ]] && outln && pr_warning "No engine or GOST support via engine with your $OPENSSL"; >
          fi
          fileout_insert_warning "engine_problem" "WARN" "No engine or GOST support via engine with your $OPENSSL"
          # Avoid clashes of OpenSSL 1.1.1 config file with our openssl 1.0.2. This is for Debian 10
          export OPENSSL_CONF=''
          return 1
     else      # we have engine support
          if [[ -n "$OPENSSL_CONF" ]]; then
               prln_warning "For now I am providing the config file to have GOST support"
          else
               OPENSSL_CONF=$TEMPDIR/gost.conf
               # see https://www.mail-archive.com/openssl-users@openssl.org/msg65395.html
               cat >$OPENSSL_CONF << EOF
# testssl config file for openssl
```

**Comment by JaneX8** [comment] 2024-12-13 14:46
> We should remove the warning upfront completely. For other servers where openssl has not the ciphers builtin we don't do that either, maybe later.
> 
> For the later: yes, we could do that. Wondering though whether we should

I still think this is a better solution.
