### ISSUE TITLE
[BUG / possible BUG] Json output "scanTime" malformed

### ISSUE THREAD

**Issue by ZuperSero** [drwetter/testssl.sh#2046] opened 2021-11-26 12:23 UTC
I ran against a large list of hosts and a large amount of them have the same issue. Then results looks fine but at the very end the `scanTime` closes the list and then appends a second time. leaving the object malformed.

`parallel --delay 2 -a ../targets -j 80 --timeout 300% ../testssl.sh --json 1>paral.log 2> names_err &`

```[ ...
{
              "id"           : "scanTime",
              "ip"           : "hostname/x.x.x.x",
              "port"         : "443",
              "severity"     : "WARN",
              "finding"      : "Scan interrupted"
          }
]
,         {
              "id"           : "scanTime",
              "ip"           : "hostname/x.x.x.x",
              "port"         : "443",
              "severity"     : "WARN",
              "finding"      : "Scan interrupted"
          }
]
```

Expected:
```[ ...
{
              "id"           : "scanTime",
              "ip"           : "hostname/x.x.x.x",
              "port"         : "443",
              "severity"     : "WARN",
              "finding"      : "Scan interrupted"
          }
]
```

I believe the problem happens because somehow `$do_json` and `$do_pretty_json` both evaluate to true in `fileout_json_footer()` and even though they should be `mutually exclusive`. I can't tell what behavior would set them both to true but I guess a possible fix for the duplication would be to set the second `if` to an `elif`  to ensure only one would be evaluated. Another fix would be to identify where `$do_json` and `$do_pretty_json` both get set to True.
```
fileout_json_footer() {
     if "$do_json"; then
          if [[ "$SCAN_TIME" -eq 0 ]]; then
               fileout_json_finding "scanTime" "WARN" "Scan interrupted" "" "" ""
          elif [[ $SEVERITY_LEVEL -lt $LOW ]] ; then
               # no scan time in --severity=low and above, also needed for Travis, hackish...
               fileout_json_finding "scanTime" "INFO" $SCAN_TIME "" "" ""
          fi
          printf "]\n" >> "$JSONFILE"
     elif "$do_pretty_json"; then # <---- here
          if [[ "$SCAN_TIME" -eq 0 ]]; then
               echo -e "          ],\n                    \"scanTime\"  : \"Scan interrupted\"\n}" >> "$JSONFILE"
          else
               echo -e "          ],\n                    \"scanTime\"  : ${SCAN_TIME}\n}" >> "$JSONFILE"
          fi
     fi
}
```

System:
```
Ubuntu 20.04.3 LTS
Linux 5.8.0-1041-azure x86_64
testssl.sh       3.1dev from https://testssl.sh/dev/
    (1b11575 2021-11-10 08:12:30 -- )
./bin/openssl.Linux.x86_64
```
Perhaps unrelated, the "Scan interrupted" is inserted even though the scan results came through with no issue, perhaps because of parallel timeout.

EDIT:
It looks like the behavior observed is caused by parallel stopping the process while the object isn't completed. Resulting in malformed  json at the end of the file. I have also observed incomplete json objects and double commas 😅
I will close the Issue soon.

**Comment by drwetter** [comment] 2021-11-26 16:50
Hi,

> It looks like the behavior observed is caused by parallel stopping the process while the object isn't completed

not sure I understand the parallel command correctly but first: why are you using parallel and not the builtin option ``--parallel``? Secondly: I only can guess what the above command means for testssl.sh (gnu parallel is/was always counter intuitive to me) but  it looks to me like you demand parallel to do output file processing and scratching your head that this fails?

**Comment by ZuperSero** [comment] 2021-11-29 15:53
Thank you very much for the quick reply.
I completely agree, I'm debugging for a colleague 🙄

Think this is the best configuration for our use case, no need for external tools.
```
export  MAX_PARALLEL = 25
./testssl.sh --connect-timeout 30 --openssl-timeout 30 --mode parallel -q --jsonfile-pretty ./outdir/ --file ./targets
```
Would it be smarter to set a lower `MAX_WAIT_TEST`, and just leave `CONNECT_TIMEOUT` and `OPENSSL_TIMEOUT` as is?

**Comment by drwetter** [comment] 2021-11-29 16:42
Myself: i can't tell bc I only randomly do mass parallel scans.

But there are may folks listening who do and maybe they have an advise.

**Comment by drwetter** [comment] 2021-11-29 16:44
In the meantime I am closing this as I indicated it's seems not a bug to me.

**Closed as completed by drwetter** 2021-11-29 16:44 UTC
