### ISSUE TITLE
Bug in TLSv1.3 detection

### ISSUE THREAD

**Issue by AllanWallace** [drwetter/testssl.sh#1301] opened 2019-08-08 09:23 UTC
Hope this is the right place for this:
Testing one of my MX with testssl.sh 3.0rc3 from https://testssl.sh/dev/ 
using "OpenSSL 1.1.1 11 Sep 2018" I get this:

TLS 1.3    not offered -- connection failed rather than downgrading to TLSv1.2

and then this:
 Negotiated protocol          TLSv1.3
 Negotiated cipher            TLS_AES_256_GCM_SHA384, 253 bit ECDH (X25519) (limited sense as client will pick)

![Bug in TLSv1 3 detection](https://user-images.githubusercontent.com/53898233/62691388-7d65d680-b9c6-11e9-986e-3d56a3640d46.png)

**Comment by drwetter** [comment] 2019-08-08 10:18
Thx, @AllanWallace . Unfortunately it's a little bit like reading from a crystal ball with this little information.

Recommend to reproduce it if not done already. Also you can see handshakes with ``--debug=4`` or the full nine yards using ``--debug=6``.

**Comment by AllanWallace** [comment] 2019-08-08 10:37
Understood!
I have attached the results for that section using the --debug=6 option
[--debug=6.txt](https://github.com/drwetter/testssl.sh/files/3481248/--debug.6.txt)

**Comment by drwetter** [comment] 2019-08-08 13:08
hmm.. works for me. In debug=6 the socket reply is just empty. That is the reason for the first TLS 1.3 result.

![Screenshot_20190808_150137](https://user-images.githubusercontent.com/8036727/62705339-7dc59800-b9ed-11e9-8ac1-5a8d36e53fe3.png)

Also I get different results.

Could you try again (just screen output) with the latest from github?

**Comment by dcooper16** [comment] 2019-08-08 14:25
I haven't seen enough information to understand what is happening, but I have a guess. Looking at the code, it is _possible_ that TLS 1.3 ClientHello messages sent using `tls_sockets()` are failing, but TLS 1.3 ClientHello messages sent using OpenSSL 1.1.1 are succeeding.

If you get the same results using the latest testssl.sh from GitHub, trying running testssl.sh again in the following two ways and show the screen output:

- Using a version of OpenSSL older than 1.1.1 (like the one that comes with testssl.sh)
- Using OpenSSL 1.1.1, but with `--ssl-native` on the testssl.sh command line.

If my guess is correct, then the results using OpenSSL 1.1.1 with `--ssl-native` will be closer to what you expected to get, and the results using an older OpenSSL (that doesn't support TLS 1.3) will show no signs that the server supports TLS 1.3 at all.

**Comment by drwetter** [comment] 2019-08-12 11:57
@AllanWallace: Thanks for reporting. But I can't reproduce it, thus I am closing it.
I'd be happy to reopen if you can reproduce it with a fresh pull.

**Closed by drwetter** 2019-08-12 11:57 UTC
Labels: waiting for more input
