### ISSUE TITLE
Invalid JSON output when server does not have a cipher order

### ISSUE THREAD

**Issue by sxxs** [drwetter/testssl.sh#769] opened 2017-06-26 13:16 UTC
I am using the current version 2.9dev (9d699d1 2017-06-22 13:39:37 -- ).
with OpenSSL 1.1.0e  16 Feb 2017" [~143 ciphers]

testssl command line:

<pre>
./testssl.sh -p -s -f -U -S -P --jsonfile-pretty=/tmp/mxtest.json --warnings=batch --openssl-timeout=10 --sneaky --fast --ip=one -t smtp ipg-ag2.cleanmail.ch:25
</pre>

on Linux server11 4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux

This server appears to have no cipher order. This results in a JSON file that has an invalid syntax. My calling script expects testssl to always generate valid JSON regardless of any errors encountered during the scan. Therefore, it fails to parse the result of the scan.

Text Output:

<pre>
Start 2017-06-26 15:06:22        -->> 195.141.89.97:25 (ipg-ag2.cleanmail.ch) <<--

 A record via            supplied IP "195.141.89.97"
 rDNS (195.141.89.97):   lba89-smtp.cloud.cleanmail.ch.
 Service set:            STARTTLS via SMTP

 Testing protocols via sockets 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    not offered -- connection failed rather than downgrading to TLSv1.1
 SPDY/NPN   (SPDY is an HTTP protocol and thus not tested here)
 HTTP2/ALPN (HTTP/2 is a HTTP protocol and thus not tested here)

 Testing ~standard cipher categories 

 NULL ciphers (no encryption)                  not offered (OK)
 Anonymous NULL Ciphers (no authentication)    not offered (OK)
 Export ciphers (w/o ADH+NULL)                 not offered (OK)
 LOW: 64 Bit + DES encryption (w/o export)     not offered (OK)
 Weak 128 Bit ciphers                          not offered (OK)
 Triple DES Ciphers (Medium)                   not offered (OK)
 High grade encryption                         not offered
 Strong grade encryption (AEAD ciphers)        not offered

 Testing robust (perfect) forward secrecy, (P)FS -- omitting Null Authentication/Encryption, 3DES, RC4 

 No ciphers supporting Forward Secrecy offered

 Testing server preferences 

 Has server cipher order?     
 195.141.89.97:25 doesn't seem to be a TLS/SSL enabled server
</pre>

JSON Output:

<pre>
{
          "Invocation"  : "testssl.sh -p -s -f -U -S -P --jsonfile-pretty=/tmp/mxtest.json --warnings=batch --openssl-timeout=10 --sneaky --fast --ip=one -t smtp ipg-ag2.cleanmail.ch:25",
          "at"          : "ps17:./bin/openssl.Linux.x86_64",
          "version"     : "2.9dev 9d699d1 from 2017-06-22",
          "openssl"     : "1.0.2-chacha from Jun 22 19:32:29 2016",
          "target host" : "ipg-ag2.cleanmail.ch",
          "port"        : "25",
          "startTime"   : "1498482381",
          "scanResult"  : [
          {
                    "service"         : "smtp",
                    "ip"              : "195.141.89.97",
                    "protocols"         : [
                            {
                                "id"           : "sslv2",
                                "severity"     : "OK",
                                "finding"      : "SSLv2 is not offered"
                           },{
                                "id"           : "sslv3",
                                "severity"     : "OK",
                                "finding"      : "SSLv3 is not offered"
                           },{
                                "id"           : "tls1",
                                "severity"     : "INFO",
                                "finding"      : "TLSv1.0 is offered"
                           },{
                                "id"           : "tls1_1",
                                "severity"     : "INFO",
                                "finding"      : "TLSv1.1 is offered"
                           },{
                                "id"           : "tls1_2",
                                "severity"     : "CRITICAL",
                                "finding"      : "TLSv1.2: connection failed rather than downgrading to TLSv1.1"
                           },{
                                "id"           : "spdy_npn",
                                "severity"     : "INFO",
                                "finding"      : "SPDY/NPN : (SPY is an HTTP protocol and thus not tested here)"
                           },{
                                "id"           : "https_alpn",
                                "severity"     : "INFO",
                                "finding"      : "HTTP2/ALPN : HTTP/2 is and HTTP protocol and thus not tested"
                           }
                    ],
                    "ciphers"           : [
                            {
                                "id"           : "std_NULL",
                                "severity"     : "OK",
                                "finding"      : "NULL ciphers (no encryption)               not offered"
                           },{
                                "id"           : "std_aNULL",
                                "severity"     : "OK",
                                "finding"      : "Anonymous NULL Ciphers (no authentication) not offered"
                           },{
                                "id"           : "std_EXPORT",
                                "severity"     : "OK",
                                "finding"      : "Export ciphers (w/o ADH+NULL)              not offered"
                           },{
                                "id"           : "std_DES+64Bit",
                                "severity"     : "OK",
                                "finding"      : "LOW: 64 Bit + DES encryption (w/o export)  not offered"
                           },{
                                "id"           : "std_128Bit",
                                "severity"     : "OK",
                                "finding"      : "Weak 128 Bit ciphers                       not offered"
                           },{
                                "id"           : "std_3DES",
                                "severity"     : "OK",
                                "finding"      : "Triple DES Ciphers (Medium)                not offered"
                           },{
                                "id"           : "std_HIGH",
                                "severity"     : "MEDIUM",
                                "finding"      : "High grade encryption                      not offered"
                           },{
                                "id"           : "std_STRONG",
                                "severity"     : "MEDIUM",
                                "finding"      : "Strong grade encryption (AEAD ciphers)     not offered"
                           }
                    ],
                    "pfs"               : [
                            {
                                "id"           : "pfs",
                                "severity"     : "MEDIUM",
                                "finding"      : "(Perfect) Forward Secrecy : No ciphers supporting Forward Secrecy offered"
                           }
                    ],
                    "serverPreferences" : [
          ],
          "scanTime"  : "0"
}
</pre>

**Comment by drwetter** [comment] 2017-06-26 14:07
The result seems incomplete as it seems the server refused your requests after a while or there's another measure in place...

Admittedly the output should be able to handle this better. I consider this an edge case though and thus more a matter of polishing.

**Comment by sxxs** [comment] 2017-06-26 14:15
I agree with you. We can handle the fact that the file is incomplete fine on our end. However, I am not sure whether you noticed the subtle syntax error:

There is the clause

<pre>
"serverPreferences" : [
</pre>

but the corresponding closing "]" is missing. Therefore, the syntax is invalid, which makes parsing much more difficult than it should be.

**Comment by drwetter** [comment] 2017-06-26 14:17
I used a JSON validator which spotted that too :-)

**Comment by drwetter** [comment] 2017-09-18 21:58
Closing this as this server is not anymore reachable and I can't reproduce it on another machine which has no cipher order either

**Comment by robertlagrant** [comment] 2018-01-18 12:21
We have exactly the same problem. Scanresult doesn't finish writing (the object doesn't close, and the array the object is in also doesn't), and it just closes with a final }.

We have no major issues detected by testssl.sh, just two lows. I'm running with defaults other than the --jsonfile-pretty argument.

We can mung it before we load as json to get round this, but thought it might be useful to report. Without munging, we can't easily run testssl.sh as part of our automated testing.

**Comment by drwetter** [comment] 2018-01-19 13:38
@robertlagrant : scanresult appears fine to me but browserSimulations misses a comma after the closing bracket.

Is there any recommendation for a command line lint for JSON?

**Comment by drwetter** [comment] 2018-01-19 14:17
Oh, my bad. I thought after ``browserSimulations": [
]`` (2.9.5) needs to be a comma. But I tried several linters and all say OK. If you happen to have more input for me to reproduce this, it would be appreciate. 

There's another strange thing though in 2.9dev I just stumbled over (#962). Semantics is broken there, syntax ok

**Comment by dcooper16** [comment] 2018-01-19 22:23
I looked into this issue a little and believe I discovered the source of the problem. It is not a result of the server not having a cipher order.

In a "normal" execution of the program, `lets_roll()` calls `fileout_section_footer true` shortly before completing. If the program is stopped before this call to `fileout_section_footer true`, then the JSON pretty output is invalid.

One way to reproduce this result is to simply stop the program (Ctrl-C) while it is running. In the scenario that started this thread, the call to `determine_optimal_proto()` from `run_server_preference()` called `exit -2` since all of its tests failed and testssl.sh was running in batch mode. This could also happen if `run_protocols()` couldn't find any offered protocols, as it would call `exit -2` if not protocol was detected.

It seems that the solution would be to add a call to `fileout_section_footer true` to `cleanup()`. It would be a non-trivial fix, though, since there would need to be a way to determine whether a call to `fileout_section_footer true` was needed, as the call could not be made in a "normal" execution. Perhaps a flag could be set to TRUE when `fileout_section_header()` was called, which would then be set to FALSE when `fileout_section_footer true` was called. Then `cleanup()` would only call  `fileout_section_footer true` if the flag were TRUE. I haven't tested this, though, so I can't be sure it would work.

**Comment by drwetter** [comment] 2018-01-22 14:45
Solution and analysis makes sense to me (one can also e.g. just pull the network cable).

Also for a clean end and a clean program it would make sense --  albeit I am not sure how process a scan which couldn't finish.  This alone is probably of limited value but I personally  can't tell (@sxxs / @robertlagrant ?)

Maybe it's better also to include a message for cleanup in fileout why testssl.sh thinks it couldn't proceed.

**Comment by drwetter** [comment] 2018-02-09 18:58
Could you please check @sxxs and @robertlagrant ? I did some tests and it looked ok to me.

I didn't add a JSON object yet signaling a connection problem or so.

**Comment by drwetter** [comment] 2018-02-23 12:55
ping

**Comment by robertlagrant** [comment] 2018-02-27 10:28
@drwetter apologies; I get so many notifications from internal company stuff that I miss people actually trying to get in touch with me :)

Comments:
1) I haven't noticed this coinciding with unexpected program exit at all (and I'm definitely not `ctrl-c`ing, for example) but I will keep an eye out
2) I'm running the code now and not getting the error, so perhaps that's good? I'll keep testing it against a few different endpoints and just see what I get.
3) Thanks for this awesome tool!

**Comment by drwetter** [comment] 2018-03-01 15:07
3: thanks for saying thanks!
2+1: please let me know, if that will happen again.

I am closing this in the meantime as i did some further tests which looked good.

**Closed by drwetter** 2018-03-01 15:07 UTC
Labels: polishing
