### ISSUE TITLE
Server side handshake limitations for TLS 1.2 (# of ciphers or size of ClientHello) 

### ISSUE THREAD

**Issue by feld** [drwetter/testssl.sh#189] opened 2015-09-10 14:02 UTC
When printing the cipher order it doesn't show all the ciphers under TLS 1.2. It only shows the first one the server prefers.

```
$ ./testssl.sh -E -P foo.com

###########################################################
    testssl.sh       2.6rc3 from https://testssl.sh/dev/
    (a9f231b 2015-09-09 16:41:32 -- 1.375)

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2d-dev)" [~181 ciphers] on
bar.com:$PWD/bin/openssl.Linux.x86_64
 (built: "Jul  6 18:05:33 2015", platform: "linux-x86_64")


Testing now (2015-09-10 08:57) ---> 207.71.137.35:443 (foo.com) <---

 rDNS (1.1.1.1):   foo.com.
 Service detected:       HTTP


--> Testing server preferences

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            AES256-SHA
 Cipher order
     TLSv1:     AES256-SHA AES128-SHA DES-CBC3-SHA
     TLSv1.1:   AES256-SHA AES128-SHA DES-CBC3-SHA
     TLSv1.2:   AES256-SHA
--> Testing all locally available ciphers per protocol against the server, ordered by encryption strength

Hexcode  Cipher Suite Name (OpenSSL)    KeyExch.   Encryption Bits        Cipher Suite Name (RFC)
-----------------------------------------------------------------------------------------------------------------------
SSLv2
SSLv3
TLS 1
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS 1.1
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS 1.2
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA
 x3c     AES128-SHA256                  RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA256
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA

```

**Comment by teward** [comment] 2015-09-10 17:47
Note: I couldn't replicate your issue.  Note that I *did* set up a local nginx server, with configurations to match the ciphers that you appear to have configured.  This is what I got, using latest Master branch:

<pre>
% testssl -E -P local-ssl-testing.dark-net.net

###########################################################
    testssl.sh       2.6rc3 from https://testssl.sh/dev/
    (a9f231b 2015-09-09 16:41:32 -- 1.375)

      This program is free software. Distribution and 
             modification under GPLv2 permitted. 
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2d-dev)" [~195 ciphers] on
 darksource:/usr/local/bin/openssl_1.0.2
 (built: "Jul  6 18:09:12 2015", platform: "linux-x86_64")


Testing now (2015-09-10 13:45) ---> 127.0.1.4:443 (local-ssl-testing.dark-net.net) <---

 rDNS (127.0.1.4):       -- (A record via /etc/hosts) 
 Service detected:       HTTP


--> Testing server preferences

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            AES256-SHA
 Cipher order
     TLSv1:     AES256-SHA AES128-SHA DES-CBC3-SHA 
     TLSv1.1:   AES256-SHA AES128-SHA DES-CBC3-SHA 
     TLSv1.2:   AES256-SHA AES128-SHA256 AES128-SHA DES-CBC3-SHA 
     http/1.1:  AES256-SHA AES128-SHA256 AES128-SHA DES-CBC3-SHA 
--> Testing all locally available ciphers per protocol against the server, ordered by encryption strength

Hexcode  Cipher Suite Name (OpenSSL)    KeyExch.   Encryption Bits        Cipher Suite Name (RFC)
-----------------------------------------------------------------------------------------------------------------------
SSLv2 
SSLv3 
TLS 1 
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA                      
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA                      
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA                     
TLS 1.1 
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA                      
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA                      
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA                     
TLS 1.2 
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA                      
 x3c     AES128-SHA256                  RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA256                   
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA                      
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA                     

Done now (2015-09-10 13:45) ---> 127.0.1.4:443 (local-ssl-testing.dark-net.net) <---
</pre>

I'd run a test against your server, but since that information's obfuscated, I can't (hence the local test environment).

**Comment by drwetter** [comment] 2015-09-10 19:00
Am 09/10/2015 um 04:02 PM schrieb Mark Felder:
> When printing the cipher order it doesn't show all the ciphers under TLS 1.2. It only shows the
> first one the server prefers.

Thomas, thx for reporting.

I somewhat sense sense foo,com or 1.1.1.1 isn't real. You gotta give me the a bit more info as
in all other cases I've seen
so far it worked.


PM is fine.


Cheers, Dirk

PS: In next stage I'll change that. Likely you'll see one cipher per protocol
where every cipher is displayed and in the end there'll be a complete wide
listing  sorted by server preference, maybe per protocol. maybe not.

Cheers, Dirk

**Comment by drwetter** [comment] 2015-09-10 19:02
Sorry, I meant thx @feld for reporting.

And thx @teward for heling here!

**Comment by drwetter** [comment] 2015-09-14 07:15
Reminder @feld: I would love to fix this RSN but I would need more info. Thx!

**Comment by PeterMosmans** [comment] 2015-09-17 08:35
@feld @drwetter @teward 
Thanks for reporting and troubleshooting so far. To keep things centrally located I'm going to use the issue at the OpenSSL fork for all communications - see https://github.com/PeterMosmans/openssl/issues/28

(I'll report back here of course when the issue is solved... :wink: )

**Comment by PeterMosmans** [comment] 2015-09-17 08:49
(text copied from the issue back over at 1.0.2-chacha)

OK, found the issue.
Cisco ASA's can't hande a handshake => 128 ciphers, and the 1.0.2-chacha fork has more than that, fortunately :smile: 
I *know* for a fact that this issue has been reported to Cisco before, however I'm unaware of the current status. Please report this to Cisco (again), maybe that will help getting the issue fixed (faster)...

How to reproduce:
Run https://github.com/PeterMosmans/security-scripts/blob/master/test_ssl_handshake.sh with the following parameters:
```
./test_ssl_handshake.sh --openssl=/path/to/openssl/1.0.2-chacha --cipherstring="ALL" --start=125 --128 TARGET

```
This will iterate over ciphers starting from 125, and it will error out when the 128 cipher limit is reached.

Funny enough was this Cisco thing the reason that I built this testscript in the first place...

**Comment by drwetter** [comment] 2015-09-23 15:33
Hi Mark,

dood that @PeterMosmans  had that much patience with me ;-)

Bottom line: He's right. Cisco can't handle that many ciphers. So you ( @feld ) can try to yell at them, I will try to work around it. Don't know when though, other things have more priority. Probably this will be not fixed in 2.6 but in dev.

Thx all,

Dirk

**Comment by PeterMosmans** [comment] 2015-09-23 22:10
:smile: Well, this finally gave me a reason to create a quick-and-dirty script to eavesdrop on SSL/TLS handshakes in the background, and show information about them.
Thanks @drwetter for being so "gründlich und pünktlich", never forsake quality :+1:

**Comment by drwetter** [comment] 2015-09-24 07:16
Nah, quality is always important to me -- also if it makes matters sometimes more complicated. ;-)

**Comment by drwetter** [comment] 2016-06-07 11:16
Hi @feld,

I have a workaround. It needs some polishing but if you supply ``SIZELMT_W_ARND=true ./testssl.sh -e -P <thehostnameyousupplied2me>`` testssl.sh will do my workaround: https://github.com/drwetter/testssl.sh/commit/8ed6214b6f2907d8fee4e566a0402f9dd88bcf06 .

Probably I'll make it smarter. If testssl would do a workaround by default it would penalize all other users because of this server side bug from Cisco and friends.

Solution for later: First I thought to ask @PeterMosmans whether I could borrow ideas from his script. But I guess it's easier if the second s_client call failed for TLS 1.2 (``s_client -cipher "ALL:-<FIRSTCIPHERDETECTED>``) to automagically do the workaround.  That would penalize only those who have one cipher for TLS 1.2 configured.

Cheers, Dirk

**Closed** 2016-06-09 09:05 UTC
Labels: bug

**Comment by drwetter** [comment] 2016-06-09 09:08
It looks like this now:

```
 Testing server preferences 

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            AES256-SHA
 Cipher order
    TLSv1:     AES256-SHA AES128-SHA DES-CBC3-SHA
    TLSv1.1:   AES256-SHA AES128-SHA DES-CBC3-SHA
    TLSv1.2:   AES256-SHA AES128-SHA256 AES128-SHA DES-CBC3-SHA
```
