### ISSUE TITLE
`--file` mode combined w/ *file arguments produces partial output files

### ISSUE THREAD

**Issue by bitsofinfo** [drwetter/testssl.sh#1148] opened 2018-10-25 21:32 UTC
Please make sure that you provide enough information so that we understand what your issue is about.

   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)

```
testssl.sh       2.9.5-7 from https://testssl.sh/
    (727a288 2018-09-20 22:05:28 -- )
```

2. what exactly was happening, output is needed

Running this produces expected files w/ proper content, fully populated

```
./testssl.sh -S -P -p --fast --htmlfile test.html --csvfile test.csv --jsonfile-pretty test.json https://www.google.com
```

Running this produces files with partial data populated.  They are not complete JSON, invalid HTML etc

```
./testssl.sh --file test.txt
```

Contents of `test.txt`

```
-S -P -p --fast --htmlfile test.html --csvfile test.csv --jsonfile-pretty test.json https://www.google.com
```

3. what did you expect instead?

When running in `--file` mode, the contents of the `test.*` files should look no different then when running in non-file mode.

4. steps to reproduce

See above
 
    1. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
 
```
testssl.sh       2.9.5-7 from https://testssl.sh/
    (727a288 2018-09-20 22:05:28 -- )
```

    1. your operating system (uname -a)

`17.6.0 Darwin Kernel Version 17.6.0`

**Comment by drwetter** [comment] 2018-10-26 07:29
yeah, there's no check of args which appear double. Wasn't aware that it affects the output which shouldn't be the case but need to check myself.

**Comment by bitsofinfo** [comment] 2018-10-26 13:34
Double args? not sure I specified any unique argument more than once. I just have need to generate all 3-4 outputs per command in the instruction files (csv, json, html and log). Only when the instruction file is used do I see this behavior, but not when straight on the command line w/ just a single command and no instruction file. (thanks for the great tool BTW!)

**Comment by dcooper16** [comment] 2018-10-26 14:09
What you are seeing is the result of the way that testssl.sh was designed, and it would be very difficult to fix. My suggestion would be to only include options related to output files in the command line, and not include them in test.txt.

To provide a more technical explanation, here is what is happening. testssl.sh implements the `--file` option by calling itself (creating a child process) for each line in the file (test.txt). The options that are sent to the child process are created by combining the options specified on the command line with those listed in the file (test.txt). In your example, the child is called with:
```
--warnings=batch -S -P -p --fast --htmlfile test.html --csvfile test.csv --jsonfile-pretty test.json https://www.google.com
```
The problem is that the child process cannot tell whether an option like `--htmlfile test.html` came from the command line or from the test.txt file, so it assumes it came from the command line.

While it may seem that it shouldn't matter in the case of your example, it would matter in the general case in which test.txt listed several tests to run (the `--file` option is intended to support mass testing). In the case of mass testing, we need to prevent the child process from adding headers or footers to test.html, since we need to ensure that test.html contains only one set of headers and one set of footers, not one for each test in test.txt. So, if `--htmlfile test.html` were provided at the command line, then the parent testssl.sh process would have added headers and footers to test.html, and the child process would be instructed to write to test.html, but to not create any headers or footers.

In the case of your example, `--htmlfile test.html` was not provided to the command line, so the parent didn't create any headers or footers, and the child process, assuming that `--htmlfile test.html` was provided at the command line, doesn't add any headers or footers either.

**Comment by bitsofinfo** [comment] 2018-10-26 14:18
I think i follow, unfortunately I was hoping for a unique outputfile (with unique name or path to it) per tested endpoint. Looking to do mass testing and feeding this upstream where 1 output file (json for example) exists per tested endpoint. Looks like I might be better off just creating my own wrapper that spawns many unique testssl.sh invocations?

**Comment by dcooper16** [comment] 2018-10-26 16:06
> I was hoping for a unique outputfile (with unique name or path to it) per tested endpoint. Looking to do mass testing and feeding this upstream where 1 output file (json for example) exists per tested endpoint.

You can do this with testssl.sh, just not in the way you were trying. Instead, you need to let testssl.sh create the file names for each of the output files. This can be done using either

```
./testssl.sh -S -P -p --fast --html --csv --json-pretty --file test.txt
```
or
```
./testssl.sh -S -P -p --fast --htmlfile <HTML output directory> --csvfile <CSV output directory> --jsonfile-pretty <JSON output directory> --file test.txt
```
Where test.txt just contains the list of endpoints to test.

If the file name provided to `--htmlfile`, `--csvfile`, or `--jsonfile-pretty` is a file, then all output will go to that file. But, if the file name is a directory, then a separate file will be created in that directory for each tested input. If `--html` is used, then a separate file will be created in the directory in which the test was run.

In the case of the example above, the file names that would be created would be of the form "www.google.com_p443-20181026-1202.html", "www.google.com_p443-20181026-1202.csv", and "www.google.com_p443-20181026-1202.json", where the file name indicates the host name and port of the end point along with the date and time that the test was started.

**Comment by bitsofinfo** [comment] 2018-10-26 16:08
Yes understood, however I wanted full control over the filename "template" 

In anycase, Im just doing a wrapper for the invocations, its not a huge deal

Really appreciate the attention and help!

**Comment by drwetter** [comment] 2018-10-26 16:13
> Yes understood, however I wanted full control over the filename "template"

You can set a prefix (partly control) with `` --outprefix`` or use ``-oA /--outF)ile`` --> full control

as the help says.

**Comment by bitsofinfo** [comment] 2018-10-26 16:15
excellent, I'll check that out, missed it!

**Comment by drwetter** [comment] 2021-02-04 20:02
Please check the latest and greatest (see PR merged above) and let us know if the problem persists.

**Closed by drwetter** 2021-02-04 20:02 UTC
Labels: to be reproduced
