### ISSUE TITLE
No true JSON output

### ISSUE THREAD

**Issue by gkroon** [drwetter/testssl.sh#1414] opened 2019-12-13 23:44 UTC
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a

`Linux pentoo 5.3.13-pentoo #2 SMP Wed Nov 27 23:04:30 CET 2019 x86_64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz GenuineIntel GNU/Linux`
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2

`testssl.sh       3.0rc5 from https://testssl.sh/dev/`

3. git log | head -1 (if running from git repo)

N/A

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'

`/usr/bin/openssl-bad`

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host

`testssl.sh --jsonfile testssl.json large.nl`

6. what exactly was happening, output is needed

```
,         {
              "id"           : "PFS_ECDHE_curves",
              "ip"           : "large.nl/85.13.161.63",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "sect283k1 sect283r1 sect409k1 sect409r1 sect571k1 sect571r1 secp256k1 prime256v1 secp384r1 secp521r1 brainpoolP256r1 brainpoolP384r1 brainpoolP512r1"
          }
         {
              "id"           : "DH_groups",
              "ip"           : "large.nl/85.13.161.63"
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "RFC3526/Oakley Group 14"
          }
```

7. what did you expect instead?

```
,         {
              "id"           : "PFS_ECDHE_curves",
              "ip"           : "large.nl/85.13.161.63",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "sect283k1 sect283r1 sect409k1 sect409r1 sect571k1 sect571r1 secp256k1 prime256v1 secp384r1 secp521r1 brainpoolP256r1 brainpoolP384r1 brainpoolP512r1"
          },
         {
              "id"           : "DH_groups",
              "ip"           : "large.nl/85.13.161.63",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "RFC3526/Oakley Group 14"
          }
```

Notice the lack of a comma (,) in between of these two blocks. The lack of this comma is what prevents me from parsing this as a JSON object.

**Comment by drwetter** [comment] 2019-12-14 08:42
Hi Guido,

thanks for the detailed description. It's only that I can't reproduce it: ``./testssl.sh --jsonfile testssl.json large.nl `` yields:

```
,         {
              "id"           : "PFS_ECDHE_curves",
              "ip"           : "large.nl/85.13.161.63",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "sect283k1 sect283r1 sect409k1 sect409r1 sect571k1 sect571r1 secp256k
1 prime256v1 secp384r1 secp521r1 brainpoolP256r1 brainpoolP384r1 brainpoolP512r1"
          }
,         {
              "id"           : "DH_groups",
              "ip"           : "large.nl/85.13.161.63",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "RFC3526/Oakley Group 14"
          }
,         {
              "id"           : "cipher_order",
```

It's not only that. If the comma would be missing Travis/Ci would have caught that, see ``t/07_isJSON_valid.t``

I am closing this. If you have more info, I am happy to reopen the issue.

Thanks, Dirk

**Closed by drwetter** 2019-12-14 08:42 UTC

**Comment by gkroon** [comment] 2019-12-14 10:08
It somehow went away when I woke up this morning and I'm starting to doubt my own sanity, lol. Anyway, thanks for looking into it!

**Comment by drwetter** [comment] 2019-12-14 15:56
sure
