### ISSUE TITLE
Wrong wildcard parsing in SAN

### ISSUE THREAD

**Issue by Rogdham** [drwetter/testssl.sh#981] opened 2018-02-06 10:56 UTC
Hello,

I'm running testssl.sh on some domain (cannot disclose it due to NDA, sorry) and the following is output:

```
 Common Name (CN)             *.placeholder.ext
 subjectAltName (SAN)         *.placeholder.ext placeholder.ext
 Issuer                       Gandi Standard SSL CA 2 (Gandi from FR)
 Trust (hostname)             via CN wildcard, but not SAN -- Browsers are complaining (same w/o SNI)
```

The issue is the message `via CN wildcard, but not SAN -- Browsers are complaining`, since the wildcard is also in SAN.

Seems like there is some error in parsing the wildcard domain from the SAN.

If you want me to perform some tests on that domain for you, feel free to ask.

***

Output from `certtool -i` on the certificate:

```
X.509 Certificate Information:
	Version: 3
--<snip>--
	Subject: CN=*.placeholder.ext,OU=Gandi Standard Wildcard SSL,OU=Domain Control Validated
--<snip>--
		Subject Alternative Name (not critical):
			DNSname: *.placeholder.ext
			DNSname: placeholder.ext
```

***

Versions (testssl.sh cloned from github, commit 364011b6ca870f0fe6139246ad943d193d073286):

```
$ testssl.sh -b 2>/dev/null | head -4 | tail -2
testssl.sh       2.9dev from https://testssl.sh/dev/
$ testssl.sh -b 2>/dev/null | head -16 | tail -3
 on placeholder:/placeholder/testssl.sh/bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")
$ uname -a
Linux placeholder 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
```

**Comment by drwetter** [comment] 2018-02-06 11:24
Thx for reporting.

@dcooper16 : would you mind looking into it?  Looks like ``compare_server_name_to_cert()`` returns 8 but should have matched earlier

**Comment by dcooper16** [comment] 2018-02-06 15:00
Hi @Rogdham , @drwetter ,

I have been unable to reproduce the error. I tried running testssl.sh on a large number of servers, and in every case testssl.sh worked correctly. One example is www.facebook.com:
```
   Common Name (CN)             *.facebook.com
   subjectAltName (SAN)         *.facebook.com *.xx.fbcdn.net *.xz.fbcdn.net facebook.com
                                *.fbsbx.com *.xy.fbcdn.net *.facebook.net *.messenger.com
                                *.fb.com fb.com *.fbcdn.net *.m.facebook.com messenger.com 
   Issuer                       DigiCert SHA2 High Assurance Server CA (DigiCert Inc from US)
   Trust (hostname)             Ok via SAN wildcard and CN wildcard (same w/o SNI)
```
At the moment I cannot be certain whether the problem is with testssl.sh or the server, but I know that testssl.sh uses the same code, `wildcard_match()`, to determine whether the CN and each DNS name in the SAN is a wildcard match against the presented name. So, if the CN and the first name in the SAN are both actually the same, it is difficult to understand how testssl.sh could determine that one is a match and the other isn't.

It seems that the most likely possibility is that the values in the CN and SAN in the certificate are not actually the same and testssl.sh is correctly reporting that the presented name does not match the SAN. Perhaps there is a small typo in the name in the SAN.

If you're certain that the names are exactly the same, then the next step would be to run testssl.sh in debug mode: `bash -x testssl.sh ...`, then look at the trace of the program (which will be in /tmp/testssl-xxxx, where xxxx is some number) for the call to `compare_server_name_to_cert`. You should see the trace get to line 6255 where the call to `wildcard_match()` is made comparing the presented name to the *.placeholder.ext in the SAN. Since testssl.sh is indicating that there is no match, there should be some point in the trace of `wildcard_match()` that it returns 1, indicating that it determined there was no match. The line that returns 1 should provide some indication of why testssl.sh determined that the name in the SAN didn't match the presented name.

**Comment by Rogdham** [comment] 2018-02-06 15:56
Hello @dcooper16, I think I found the issue thanks to your answer!

To reproduce:
```
$ mkdir /tmp/testssl_bug
$ cd /tmp/testssl_bug
$ touch blahblah.facebook.com
$ testssl.sh www.facebook.com
```

The issue seems to be with wildcard completion in bash.

In line 6238: `for san in $dns_sans; do`, if `$dns_sans` contains `*.facebook.com` and there are some files in the directory matching `*.facebook.com` (in the example, `blahblah.facebook.com`), then it will get into `$san`.

Tell me if that makes sense to you!

**Comment by dcooper16** [comment] 2018-02-06 16:55
Hi @Rogdham ,

Thanks for looking into this. This does seem to be a minor bug in testssl.sh. Another way to reproduce the bug is:
```
testssl.sh --logfile blah.facebook.com -S www.facebook.com
```
As you noted, the `for` loop should be comparing the presented name to `*.facebook.com`, `*.xx.fbcdn.net`, `*.xz.fbcdn.net`, etc. Instead, it is comparing the presented name to `blah.facebook.com`, `*.xx.fbcdn.net`, `*.xz.fbcdn.net`, etc.

I believe that I found a way to fix the problem, but I need to do some testing to try to ensure that the fix doesn't create a new problem.

**Comment by dcooper16** [comment] 2018-02-06 19:18
I just submitted a PR (#982) that fixes this issue. I ran the program in debug mode as above and "blahblah" doesn't show up anywhere else, so hopefully the issue of wildcard completion won't create problems anywhere else.

@Rogdham : There is no need to invoke testssl.sh as
```testssl.sh xxx.placeholder.ext | tee testssl_xxx.placeholder.ext```

You can get the same result using the `--logfile` option:
```testssl.sh --logfile testssl_xxx.placeholder.ext xxx.placeholder.ext```

You could also use the `--log` option and let testssl.sh create the file name, or use `--html` or `--htmlfile` to get an HTML version of the output.

**Closed** 2018-02-08 10:39 UTC
Labels: possible bug (unconfirmed)

**Comment by Rogdham** [comment] 2018-02-08 12:23
I'm confirming that the issue is solved, thanks @dcooper16!
