### ISSUE TITLE
Session Resumption test sometimes fails with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#948] opened 2017-12-21 15:49 UTC
When using the `-S` option and testing with OpenSSL 1.1.1, the Session Resumption test fails sometimes:
```
 Session Resumption           Ticket resumption test failed, pls report / ID resumption test failed, pls report
```
or
```
 Session Resumption           Tickets: yes, ID resumption test failed, pls report
```
As far as I can tell the problem occurs when the first call to `$OPENSSL s_client` in `sub_session_resumption()` does not write any data to `$sess_data` and then the second call fails with an error indicating that it cannot open the input file `$sess_data`.

Tracing through two different versions of OpenSSL, it seems that earlier versions of OpenSSL will always create a `$sess_data` file in response to `-sess_out $sess_data`, whereas OpenSSL 1.1.1 will only create a `$sess_data` file if there is a session identifier (i.e., if `s->session->session_id_length > 0`).

I don't understand how `sub_session_resumption()` works, but it seems that there needs to be a check after the first call to `$OPENSSL s_client` in `sub_session_resumption()` to see whether `$sess_data` is present and non-empty, and to assume no session resumption if it isn't.

**Comment by drwetter** [comment] 2017-12-31 20:18
resolved via  0964cbc5d35bcb98591cf982249d6c22037c94d6 and
a3b4609d24b3ccc910d27bbe15e84aea4735ed32

**Comment by drwetter** [comment] 2018-02-05 18:52
still facing a problem here, with ``cloudflare.com`` which behaves different if I use openssl 1.0.2 instead.

**Comment by drwetter** [comment] 2019-02-22 16:35
can't reproduce anymore on ``cloudfare.com`` with _any_ openssl version

**Closed by drwetter** 2019-02-22 16:35 UTC
Labels: minor bug
