### ISSUE TITLE
How to make it silent?

### ISSUE THREAD

**Issue by vitz3** [drwetter/testssl.sh#148] opened 2015-07-24 17:13 UTC
I wanted to use this tool (good work btw) in parallel across like a trillion hosts and ports. Unfortunately it appears this tool is chatty. No news is good news and the banner/version information after each run is extra noise to parse out. Is there a q flag or something missing by chance?

**Comment by drwetter** [comment] 2015-07-24 20:09
> I wanted to use this tool (good work btw) 

(thx, appreciated)

>  in parallel across like a trillion hosts and ports. Unfortunately it appears this tool is chatty. 
> No news is good news and the banner/version information after each run is extra noise to parse 
> out. Is there a q flag or something missing by chance?

Not yet/ But it's a good idea If I do testing I help myself with
``` 
./testssl.sh --sneaky --warnings batch --ip=one $* $hname | sed '/#########################################################/,/platform: "linux-x86_64")/d'
```

which filters the banner. I am redirecting the output anyway to e.g. have the possibility to do a diff or do other things/

In fact that filtering done by sed above can be easier achieved by ``-q``. That's not a bug deal and I can do that in the near future. More -- i.e. showing only negative results -- needs more consideration.

In mid terms I had in mind for mass testing to read the commands from a file and just have one banner. No big deal too. But not in the next two weeks or so.

**Comment by drwetter** [comment] 2015-07-25 12:34
@vitz3 : give it a try if you like.

**Comment by drwetter** [comment] 2015-08-14 12:01
implemented, thus closing

**Closed by drwetter** 2015-08-14 12:01 UTC
Labels: enhancement
