### ISSUE TITLE
testssl.sh prints with invisible ink

### ISSUE THREAD

**Issue by dilyanpalauzov** [drwetter/testssl.sh#1928] opened 2021-07-06 07:04 UTC
On my system calling `./testssl.sh` prints:
```

###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (56dcbcd 2021-06-22 08:25:29 -- )
```

The text in brackets `56dcbcd 2021-06-22 08:25:29 -- ` is printed in black color on black background and is therefore invisible.  The brackets are visible.

**Comment by drwetter** [comment] 2021-07-08 10:27
Hi Dilyan,

works for me.

xterm:
![image](https://user-images.githubusercontent.com/8036727/124906596-84008c80-dfe7-11eb-8fbf-c48d404d0818.png)

konsole:
![image](https://user-images.githubusercontent.com/8036727/124906656-95e22f80-dfe7-11eb-9747-22ada0f7563e.png)

gnome-terminal: can tell bc I am (as Joe average user) not able to switch to a black background.

Thus I am closing it. Happy to reopen if you provide more information.

Cheers, Dirk

**Comment by drwetter** [comment] 2021-07-08 10:40
To add a bit of info: The xterm had just 16 colors, konsole 256.

**Comment by dilyanpalauzov** [comment] 2021-07-12 06:05
![testssl-black](https://user-images.githubusercontent.com/4992947/125238775-5ae64180-e2f0-11eb-819b-8b79235f5f1b.png)

**Comment by dilyanpalauzov** [comment] 2021-07-12 06:06
This is from gnome-terminal with its default settings under Fedora.

**Comment by drwetter** [comment] 2021-07-12 14:39
Strange. :-/

What's the content of the TERM variable?

**Comment by dilyanpalauzov** [comment] 2021-07-12 14:51
```
$ echo $TERM
screen
```

**Comment by dilyanpalauzov** [comment] 2021-07-12 14:51
I am running the command within tmux session.

**Comment by drwetter** [comment] 2021-07-12 18:15
Well, IIRC the capabilities for TERM=screen are rather limited. 

On both screen and tmux you should be better off using TERM=screen-256color.

We don't support that much colors yet but you should be able to see grey. 

For the UI we maybe should issue a warning if such a simple terminal is discovered.

**Comment by dilyanpalauzov** [comment] 2021-07-12 21:55
I provided real case scenario, where testssl.sh prints with invisible ink.

The problem will disappear, if green, yellow, white is used instead, or just normal grey.  E.g. the line
` Has server cipher order?     yes (OK) -- TLS 1.3 and below`
contains white at the beginning, green in the middle and visible grey at the end.

Using that particular nuance of grey is not ultimately necessary.  If it is used, then use it also for the surrounding brackets, so that screen users do not notice missing text.

**Comment by drwetter** [comment] 2021-07-13 07:54
Whether it's ultimately necessary lies in the eyes of the beholder. ;-)

I can look into this next week but still my personal recommendation is GENERALLY using a terminal definition which is adequate and not unnecessarily below par



Am 12. Juli 2021 23:55:34 MESZ schrieb "Дилян Палаузов" ***@***.***>:

**Comment by dilyanpalauzov** [comment] 2021-07-13 09:32
See also https://github.com/tmux/tmux/issues/2773.

**Comment by drwetter** [comment] 2021-07-30 16:29
I thought first issuing a warning upfront when a screen|vt100|vt220 terminal is encountered.

However after sleeping over it, I think testssl.sh shouldn't compensate all user side problems.

In general it might not even be the person sitting in front of the computer. In this case it seems to be some weird setting in gnome. I can reproduce this with screen and a gnome-terminal when I set TERM=screen . It works in KDEs konsole and xterm.
All of them use inverse video instead of italic though.

The latter could be fixed if I would know how to determine terminal capabilities OS independently with bash.

**Closed as completed by drwetter** 2021-07-30 16:29 UTC
