### ISSUE TITLE
sessionresumption_ID: check failed

### ISSUE THREAD

**Issue by veronicapr** [drwetter/testssl.sh#2161] opened 2022-04-19 14:28 UTC
**Which version are you referring to**
v3.0.7

Getting a `sessionresumption_ID: check failed, pls report` while executing the following command:

`testssl/testssl.sh -e -E -s -p -g -S -c -h -U -P --full --pfs --rc4 --hints --warnings off --wide --show-each --openssl file.json --htmlfile file.html <ipaddress>:<port>`

The target is a 1st generation Siemens Comfort Panel.

**Comment by drwetter** [comment] 2022-04-24 08:54
Thanks for reporting. The problem is: I can't reproduce it as I don't have access to such a panel .

Secondly: it's not a common device and I'd rather say thanks, but due to that it's a won't fix.

Am 19. April 2022 16:28:40 MESZ schrieb veronicapr ***@***.***>:

**Closed as completed** 2022-04-24 15:57 UTC
Labels: wontfix
