### ISSUE TITLE
Provide better Dockerfile which doesn't require git clone or COPYing the whole local dir

### ISSUE THREAD

**Issue by u1735067** [drwetter/testssl.sh#1559] opened 2020-04-03 18:27 UTC
Hello, 

I think there's a problem with the (useful) Docker build, the tag seems to be meaningless, as the default branch is always cloned:

```
[root@vagrant-centos-docker tmp]# docker pull drwetter/testssl.sh:3.0
3.0: Pulling from drwetter/testssl.sh
aad63a933944: Already exists
c63c47aad81f: Pull complete
353a7e5fb361: Pull complete
efa9af9c6c6c: Pull complete
a85fb641c95b: Pull complete
3e7377ad23ae: Pull complete
Digest: sha256:01ffeec787b2ad48a47658df6f65d51bc066c5883054d6d536d546c7c98555ae
Status: Downloaded newer image for drwetter/testssl.sh:3.0
docker.io/drwetter/testssl.sh:3.0
[root@vagrant-centos-docker tmp]# docker run --rm -it drwetter/testssl.sh:3.0 -b

###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (8ff4520 2020-03-25 18:28:03 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]
 on f9b0294f5c0e:/home/testssl/bin/openssl.Linux.x86_64
 (built: "Jan 18 17:12:17 2019", platform: "linux-x86_64")
```

By reading hub's doc (https://docs.docker.com/docker-hub/builds/advanced/), it seems the Dockerfile could be written as:

```Dockerfile
FROM alpine:3.11

RUN apk update && apk upgrade && apk add --no-cache bash procps drill git coreutils libidn curl

RUN addgroup testssl
RUN adduser -G testssl -g "testssl user"  -s /bin/bash -D testssl

RUN ln -s /home/testssl/testssl.sh /usr/local/bin/

USER testssl
WORKDIR /home/testssl/

RUN git clone --depth=1 https://github.com/drwetter/testssl.sh.git . \
    && if [ -n "${SOURCE_BRANCH}" ]; then git fetch -f --depth=1 origin "${SOURCE_BRANCH}" && git checkout -f FETCH_HEAD; fi

ENTRYPOINT ["testssl.sh"]

CMD ["--help"]
```

Thank you for this tool, 
Best,

**Comment by u1735067** [comment] 2020-04-03 18:32
Or even better:
```dockerfile
RUN if [ -n "${SOURCE_BRANCH}" ]; then git clone --depth=1 --branch "${SOURCE_BRANCH}" https://github.com/drwetter/testssl.sh.git . ; \
    else git clone --depth=1 https://github.com/drwetter/testssl.sh.git . ; fi
```

**Comment by drwetter** [comment] 2020-04-04 18:38
Thanks @Alex131089 .

I rewrote the branch autobuilds @ dockerhub. There was in fact something not correct. However it doesn't seem well documented.

Now e.g. I see dockerhub builds for latest with the github hash dbff4a3 @ docker hub -- which is the latest commit from David. But when I pull and exec it the testssl.sh banner shows 8ff4520.

I deleted everything and started over and look later again into it.

If you or anybody else has proper documentation what I am supposed to configure in @ dockerhub, please let me know!

Not sure whether your suggestion helps for not pulling the latest commit.

**Comment by drwetter** [comment] 2020-05-06 07:54
This is still fishy. :-( 

If I do a  commit, a build is automatically triggered at github

![Screenshot_20200506_094427](https://user-images.githubusercontent.com/8036727/81149314-471dad80-8f7e-11ea-818e-d4898f12c398.png)

However when  I run the build I see it's old:

```
prompt>  git pull
Already up to date.
prompt> ./testssl.sh -b

###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (693cb21 2020-05-06 09:18:51 -- )
[..]
prompt> docker run --rm -ti  drwetter/testssl.sh:3.1dev  -b   
Unable to find image 'drwetter/testssl.sh:3.1dev' locally
3.1dev: Pulling from drwetter/testssl.sh
cbdbe7a5bc2a: Already exists
f9926bfbc9e1: Pull complete
be40cc23091e: Pull complete
7e2ccb7b62b6: Pull complete
7d561570dd73: Pull complete
97e8bcf75d49: Pull complete
Digest: sha256:a7febd0d63e737b0304bbc326b5beb8a22de41549ea2cfcaa35a4f8ea7773488
Status: Downloaded newer image for drwetter/testssl.sh:3.1dev

###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (1a6abb6 2020-04-24 09:41:59 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
[..]
prompt> git log | grep -E '^commit|^Date' | grep -n 1a6abb6                                                                                                           
105:commit 1a6abb6ab88f4bf686308fb04adbfd6358e00d3e

```

So the image pulled was 52 commits old but dockerhub tells me a build is triggered (as expected) every time I do a commit.

What is wrong here?

**Comment by u1735067** [comment] 2020-05-06 19:44
Do you have any build log?
I've never used the Docker build system sadly :/

* Maybe disabling build caching (https://docs.docker.com/docker-hub/builds/#configure-automated-build-settings)
* But by reading the docs it seems it could be simpler : 
  > Note: When Docker Hub pulls a branch from a source code repository, it performs a shallow clone (only the tip of the specified branch). Refer to Advanced options for Autobuild and Autotest for more information.

-> `RUN git clone --depth=1 https://github.com/drwetter/testssl.sh.git .`  
could be written as  
`COPY . ./`
as the build system would already have cloned the repo at the correct branch (and per https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache, the files would be detected as changed, without disabling cache)

**Comment by drwetter** [comment] 2020-05-07 09:21
Thanks, I need to go through this again. The interface of dockerhub is not really intuitive but I was always at the point "now I got it" but it turned out that wasn't really true ;-( 

```
prompt> docker run --rm -ti drwetter/testssl.sh:3.0  -b    
Unable to find image 'drwetter/testssl.sh:3.0' locally
3.0: Pulling from drwetter/testssl.sh
cbdbe7a5bc2a: Pull complete 
cf8d74500c8a: Pull complete 
c88a24efcb0e: Pull complete 
b4cedd25b6c6: Pull complete 
f9bc94012c5d: Pull complete 
8d2b22925624: Pull complete 
Digest: sha256:e81a8e8e0fd0181c680e4a9b9e04c1dd13d212e0269879108ae556309d733702
Status: Downloaded newer image for drwetter/testssl.sh:3.0

###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (1a6abb6 2020-04-24 09:41:59 -- )
````

> Do you have any build log?

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
Switched to a new branch '3.0'
Pulling cache layers for index.docker.io/drwetter/testssl.sh:3.0...
Done!
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'18.03.1-ee-3', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2018-08-30T18:42:30.000000000+00:00', u'ApiVersion': u'1.37', u'MinAPIVersion': u'1.12', u'GitCommit': u'b9a5c95', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.10.2'}}]
Arch: amd64
BuildTime: 2018-08-30T18:42:30.000000000+00:00
ApiVersion: 1.37
Platform: {u'Name': u''}
Version: 18.03.1-ee-3
MinAPIVersion: 1.12
GitCommit: b9a5c95
Os: linux
GoVersion: go1.10.2
Starting build of index.docker.io/drwetter/testssl.sh:3.0...
Step 1/10 : FROM alpine:3.11
---> f70734b6a266
Step 2/10 : RUN apk update && apk upgrade && apk add --no-cache bash procps drill git coreutils libidn curl
---> Using cache
---> 676993836a50
Step 3/10 : RUN addgroup testssl
---> Using cache
---> 84e981b75bf2
Step 4/10 : RUN adduser -G testssl -g "testssl user" -s /bin/bash -D testssl
---> Using cache
---> dc0632e90314
Step 5/10 : RUN ln -s /home/testssl/testssl.sh /usr/local/bin/
---> Using cache
---> 07d2e72e9cc3
Step 6/10 : USER testssl
---> Using cache
---> 16ee11eb2232
Step 7/10 : WORKDIR /home/testssl/
---> Using cache
---> 18dbfc037dcc
Step 8/10 : RUN git clone --depth=1 https://github.com/drwetter/testssl.sh.git .
---> Using cache
---> e706e1fc0ac3
Step 9/10 : ENTRYPOINT ["testssl.sh"]
---> Using cache
---> 14426263671a
Step 10/10 : CMD ["--help"]
---> Using cache
---> f1a72a0f914c
Successfully built f1a72a0f914c
Successfully tagged drwetter/testssl.sh:3.0
Pushing index.docker.io/drwetter/testssl.sh:3.0...
Done!
Build finished
```

**Comment by u1735067** [comment] 2020-05-07 09:23
> Step 8/10 : RUN git clone --depth=1 https://github.com/drwetter/testssl.sh.git .
> ---> **Using cache**
> ---> e706e1fc0ac3

-> I think you should try the last change I proposed (COPY the already fetched files instead of RUN git clone)

**Comment by drwetter** [comment] 2020-05-08 07:26
Thanks @Alex131089 . Your proposed change (yesterday implemented in 3.0) did it!

**Comment by drwetter** [comment] 2020-05-08 08:38
The problem is of course that COPY does a whole copy of the directory. This is fine for the automated build @ dockerhub.  But it is not always fine for local usage. Then and also depending on your system and whether testssl.sh set to 755 you may not be able to exec testssl.sh on the copy (_standard_init_linux.go:211: exec user process caused "permission denied"_).

So I reverted the PR. 

But I disabled the build cache @ dockerhu which was on (per default) as you mentioned before.  It's still kind of ugly because it clones the repo which dockerhub already has. 

If you have any better idea for a common Dockerfile  @Alex131089 pls let me know.

**Comment by drwetter** [comment] 2020-05-08 09:23
PS: your SOURCE_BRANCH hacks didn't work for the 3.0 branch.

**Comment by drwetter** [comment] 2020-05-08 09:54
Status is now that the builds work as expected -- thanks @Alex131089 for your input!

It is still kind of ugly though because the git clone seems unnecessary. OTOH the COPY command is only nice if there's a freshly cloned repo with proper ACLs for testssl.sh

**Comment by u1735067** [comment] 2020-05-08 15:46
> The problem is of course that COPY does a whole copy of the directory. This is fine for the automated build @ dockerhub. But it is not always fine for local usage.

I'm not sure I understood ; do you mean that you have to clone the repo (or a branch) to build the image, instead of being able to build it with the `Dockerfile` alone?  
Also, `git` can now be removed from the image.

> Then and also depending on your system and whether testssl.sh set to 755 you may not be able to exec testssl.sh on the copy (standard_init_linux.go:211: exec user process caused "permission denied").

Yes, when I proposed this version I wasn't sure it would work out of the box ; another version of the Dockerfile would be:
```Dockerfile
FROM alpine:3.11

COPY . /home/testssl/

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash procps drill coreutils libidn curl \
    && addgroup testssl \
    && adduser -G testssl -g "testssl user"  -s /bin/bash -D testssl \
    && ln -s /home/testssl/testssl.sh /usr/local/bin/ \
    && chmod +x /home/testssl/testssl.sh

USER testssl
WORKDIR /home/testssl/

ENTRYPOINT ["testssl.sh"]
CMD ["--help"]
```

This should work and use very few layers :)

And as COPY is the first command, there's no cache at all if any repo file is changed, which you might ou might not want.

Another version that allows caching common parts (but the image might keep outdated apk packages over time, I don't know how they handle the cache duration):
```Dockerfile
FROM alpine:3.11

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash procps drill coreutils libidn curl \
    && addgroup testssl \
    && adduser -G testssl -g "testssl user"  -s /bin/bash -D testssl

WORKDIR ~testssl/
COPY . ./

RUN ln -s ~testssl/testssl.sh /usr/local/bin/ \
    && chmod +x ./testssl.sh

USER testssl


ENTRYPOINT ["testssl.sh"]
CMD ["--help"]
```

> PS: your SOURCE_BRANCH hacks didn't work for the 3.0 branch.

When reading the docs (https://docs.docker.com/docker-hub/builds/advanced/#environment-variables-for-building-and-testing) I wasn't sure as it's mentioned for testing, but it seems you need to declare you use them :/

> OTOH the COPY command is only nice if there's a freshly cloned repo

I think that's related to the first part I didn't get, and I still don't 😅

#1627 have drawbacks:
* you still have to disable the cache or the same will happen
* you have to change one more file each time you create a new branch

**Comment by drwetter** [comment] 2020-05-08 16:19
Nevermind  😅 .

For a user which initially cloned the repo a longer time ago and still has more or less junk in there, the COPY command copies all that stuff into the container. 

I know it is maybe not best practise do a  ``docker build .`` from there. But to give you a picture: In a self experiment I dared to do so and the image was >500 megs. More over in my case the access rights for testssl.sh in the container weren't correct. I my dir it's 750, I guess it will be copied over as root and executed as "testssl" user. That won't work (can probably be changed though with chmod in Dockerfile).

I just figured that this is more ugly than the git clone command.

>   you still have to disable the cache or the same will happen

The was a slider which was on by default. As long as I don't setup new build rules that won't change I strongly hope).

>    you have to change one more file each time you create a new branch

That's true but I am changing so many files in this project that one more doesn't matter.

It's just bugging me now that each solution is kind of ugly. Only when COPY can be made working without the drawback.


PS: Yes, the layers can be reduced.

**Comment by u1735067** [comment] 2020-05-08 16:29
> I just figured that this is more ugly than the git clone command.

I prefer the COPY solution personally :p

I used a simple `COPY .`, but you can be selective be specifying all useful the path to copy, and/or a `.dockerignore` might help.

**Comment by drwetter** [comment] 2020-05-08 18:13
Nah, ``.dockerignore `` is a blacklist, so it can't reflect what people have out there.

BasicallY I'd prefer COPY, too. Currently I am struggling (COPY commands separated deliberately for demonstration purposes) :

```
prompt> cat Dockerfile
[..]
COPY --chown=testssl:testssl etc/ bin/ /home/testssl/
COPY --chown=testssl:testssl testssl.sh  /home/testssl/
[.. ]
# use CMD instead of ENTRYPOINT
[..]
> prompt>  docker build --no-cache .
[..]
 ---> Running in 9ebf662bbd0b
Removing intermediate container 9ebf662bbd0b
 ---> dbfde129e5a5
Successfully built dbfde129e5a5
> docker run -ti dbfde129e5a5 /bin/bash
bash-5.0$ ls -la
total 20196
drwxr-sr-x 1 testssl testssl    4096 May  8 18:04 .
drwxr-xr-x 1 root    root       4096 May  8 18:04 ..
-rw-r----- 1 testssl testssl  286678 Jan 15 10:52 Apple.pem
-rw-r----- 1 testssl testssl  135124 Jan 15 10:52 Java.pem
-rw-r----- 1 testssl testssl  200061 Jan 15 10:52 Linux.pem
-rw-r----- 1 testssl testssl  671654 Jan 15 10:52 Microsoft.pem
-rw-r----- 1 testssl testssl  223687 Jan 15 10:52 Mozilla.pem
-rw-r----- 1 testssl testssl    6279 Jan 18  2019 OPENSSL-LICENSE.txt
-rw-r----- 1 testssl testssl    2466 May  8 16:56 README.md
-rw-r----- 1 testssl testssl    5962 Jan 18  2019 Readme.md
-rw-r----- 1 testssl testssl   60061 Jan 15 10:52 ca_hashes.txt
-rw-r----- 1 testssl testssl   28348 Jan 11 10:41 ca_hashes.txt.bak
-rw-r----- 1 testssl testssl   71005 Oct 29  2019 cipher-mapping.txt
-rw-r----- 1 testssl testssl  239509 May  8 16:56 client-simulation.txt
-rw-r----- 1 testssl testssl    2262 Jan 17 15:05 client-simulation.wiresharked.md
-rw-r----- 1 testssl testssl   48969 May  8 16:56 client-simulation.wiresharked.txt
-rw-r----- 1 testssl testssl   52655 Oct 29  2019 common-primes.txt
-rw-r----- 1 testssl testssl     610 Jan 18  2019 curves.txt
-rw-r----- 1 testssl testssl   16308 Jan 18  2019 fedora-dirk-ipv6.diff
-rw-r----- 1 testssl testssl    4829 Jan 18  2019 krb5-ciphers.txt
-rw-r----- 1 testssl testssl    9370 Jan 18  2019 new-ciphers.diffed2vanilla.txt
-rw-r----- 1 testssl testssl   18134 Jan 18  2019 new-ciphers.std_distro.txt
-rw-r----- 1 testssl testssl   14134 Jan 18  2019 openssl-Vall.krb.txt
-rw-r----- 1 testssl testssl   18951 Jan 18  2019 openssl-Vall.txt
-rwxr-x--- 1 testssl testssl 2867628 Oct 29  2019 openssl.Darwin.x86_64
-rwxr-x--- 1 testssl testssl 4062984 Oct 29  2019 openssl.FreeBSD.amd64
-rwxr-x--- 1 testssl testssl 3424768 Oct 29  2019 openssl.Linux.i686
-rwxr-x--- 1 testssl testssl 4009248 Oct 29  2019 openssl.Linux.x86_64
-rwxr-x--- 1 testssl testssl 3112456 Oct 29  2019 openssl.Linux.x86_64.krb
-rwxr-x--- 1 testssl testssl 1004313 May  8 16:56 testssl.sh
-rwxr-x--- 1 testssl testssl   26170 Jan 15 10:52 tls_data.txt
bash-5.0$ exit
```
The directories ``etc`` and ``bin`` weren't copied recursively as expected.

What is my problem understanding this here (see also  https://docs.docker.com/engine/reference/commandline/cp/)?? I tried other combinations (slash in front, w/o traling slash) too w/o success.

**Comment by drwetter** [comment] 2020-05-09 11:26
I just created the dirs first. Thus I am closing this. If you @Alex131089  have a better (proven) suggestion, please just post it here. Or suggest a PR.

This is better as it doesn't use ``git clone`` anymore. But the (minor) catch with this is that the hash of the release is not in the banner ;-/ -- it is retrieved by ``git log`` in testssl.sh. Don't know whether one can fake this by copying a directory like (``./.git/logs/refs/remotes/origin/3.1dev``)

Thanks for the discussion and raising the issue in the first place, @Alex131089 !

**Closed as completed by drwetter** 2020-05-09 11:26 UTC

**Comment by u1735067** [comment] 2020-05-09 23:54
Is https://docs.docker.com/engine/reference/builder/#copy any more helpful?

Also https://docs.docker.com/engine/reference/builder/#dockerignore-file can work as a whitelist: 
```
**/*
!bin
!etc
!testssl.sh
```

Anyway, thank you for taking the time to include a fix for this :)

**Comment by drwetter** [comment] 2020-05-12 09:27
> Also https://docs.docker.com/engine/reference/builder/#dockerignore-file can work as a whitelist

[..]

It works currently and not that bad. So while in theory you might have a point I am not tempted at the moment to further look into it as there are other things on my table :-). A PR or anything else with more practical relevance would be more convincing.
